# SPDX-FileCopyrightText: 2026 PythonWoods <dev@pythonwoods.dev>
# SPDX-License-Identifier: Apache-2.0
"""Sovereign Cartographer — AST-based module mapper for AI context generation.

CEO-242: Provides pure functions for scanning Python source trees and
updating the [CODE MAP] section in ZENZIC_BRAIN.md.

Pillars:
  1. Lint the Source — operates on raw .py files, no build artefacts.
  2. Zero Subprocesses — 100% pure Python, no os.system / subprocess.
  3. Pure Functions First — scan_python_sources() is deterministic; I/O is
     isolated at the edges (caller / CLI layer), never inside scan loops.
"""

from __future__ import annotations

import ast
from dataclasses import dataclass, field
from pathlib import Path


MAP_START = "<!-- MAP_START -->"
MAP_END = "<!-- MAP_END -->"


@dataclass
class ModuleInfo:
    """Structured representation of a Python module extracted via AST."""

    rel_path: str
    classes: list[str] = field(default_factory=list)
    public_functions: list[str] = field(default_factory=list)
    docstring: str = ""


def _extract_info(path: Path, src_root: Path) -> ModuleInfo:
    """Parse a single .py file and return its ModuleInfo (pure — no side effects)."""
    rel = str(path.relative_to(src_root))
    try:
        source = path.read_text(encoding="utf-8")
        tree = ast.parse(source)
    except (SyntaxError, OSError):
        return ModuleInfo(rel_path=rel, docstring="[SYNTAX ERROR]")

    classes: list[str] = []
    functions: list[str] = []

    for node in ast.iter_child_nodes(tree):
        if isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
            classes.append(node.name)
        elif isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
            if not node.name.startswith("_"):
                functions.append(node.name)

    raw_doc = ast.get_docstring(tree) or ""
    doc = raw_doc.splitlines()[0].strip() if raw_doc else ""

    return ModuleInfo(rel_path=rel, classes=classes, public_functions=functions, docstring=doc)


def scan_python_sources(target_dir: Path) -> list[ModuleInfo]:
    """Scan all .py files under target_dir via AST.

    Returns a sorted list of ModuleInfo (pure function — reads files, but
    performs no writes or network calls in the scan loop).

    Excludes:
      - ``__init__.py`` (no public API surface to document)
      - Files inside directories named ``tests`` or ``test``
      - ``__pycache__`` directories
    """
    all_py = sorted(target_dir.rglob("*.py"))
    filtered = [
        p
        for p in all_py
        if p.name != "__init__.py"
        and "tests" not in p.parts
        and "test" not in p.parts
        and "__pycache__" not in str(p)
    ]
    return [_extract_info(p, target_dir) for p in filtered]


def render_markdown_table(modules: list[ModuleInfo]) -> str:
    """Render a Markdown table from a list of ModuleInfo.

    Returns the full [CODE MAP] content block (without MAP_START/MAP_END markers).
    Pure function — no I/O.
    """
    lines = [
        "### Module Quick Index",
        "",
        "> Auto-generated by `zenzic brain map` via AST (CEO-242 — Sovereign Cartographer).",
        "> Update with `just brain-map` after any change to `src/`.",
        "",
        "| File | Classes | Public Functions | Note |",
        "|------|---------|-----------------|------|",
    ]
    for mod in modules:
        classes_str = ", ".join(f"`{c}`" for c in mod.classes) or "—"
        funcs_str = ", ".join(f"`{f}`" for f in mod.public_functions) or "—"
        note = mod.docstring or "[⚠️ UNDOCUMENTED]"
        lines.append(f"| `{mod.rel_path}` | {classes_str} | {funcs_str} | {note} |")

    return "\n".join(lines)


def update_ledger(ledger_path: Path, map_block: str) -> bool:
    """Replace the content between MAP_START and MAP_END in ledger_path.

    Returns True if the ledger was updated, False if the content was already
    identical (idempotent — safe to call on every save).

    Raises ValueError if the MAP_START / MAP_END markers are not found.
    """
    text = ledger_path.read_text(encoding="utf-8")
    start_idx = text.find(MAP_START)
    end_idx = text.find(MAP_END)

    if start_idx == -1 or end_idx == -1:
        raise ValueError(
            f"Markers {MAP_START!r} or {MAP_END!r} not found in {ledger_path}. "
            "Add the markers to ZENZIC_BRAIN.md before running 'zenzic brain map'."
        )

    new_block = f"{MAP_START}\n{map_block}\n{MAP_END}"
    new_text = text[:start_idx] + new_block + text[end_idx + len(MAP_END) :]

    if new_text == text:
        return False  # already up to date — skip write

    ledger_path.write_text(new_text, encoding="utf-8")
    return True
