# SPDX-FileCopyrightText: 2026 PythonWoods <dev@pythonwoods.dev>
# SPDX-License-Identifier: Apache-2.0
"""Sovereign Cartographer — AST-based module mapper for AI context generation.

CEO-242: Provides pure functions for scanning Python source trees and
updating the [CODE MAP] section in ZENZIC_BRAIN.md.

Pillars:
  1. Lint the Source — operates on raw .py files, no build artefacts.
  2. Zero Subprocesses — 100% pure Python, no os.system / subprocess.
  3. Pure Functions First — scan_python_sources() is deterministic; I/O is
     isolated at the edges (caller / CLI layer), never inside scan loops.
"""

from __future__ import annotations

import ast
import dataclasses
import json
import re
import tomllib
from dataclasses import dataclass, field
from pathlib import Path


MAP_START = "<!-- MAP_START -->"
MAP_END = "<!-- MAP_END -->"


@dataclass
class ModuleInfo:
    """Structured representation of a Python module extracted via AST."""

    rel_path: str
    classes: list[str] = field(default_factory=list)
    public_functions: list[str] = field(default_factory=list)
    docstring: str = ""


def _extract_info(path: Path, src_root: Path) -> ModuleInfo:
    """Parse a single .py file and return its ModuleInfo (pure — no side effects)."""
    rel = str(path.relative_to(src_root))
    try:
        source = path.read_text(encoding="utf-8")
        tree = ast.parse(source)
    except (SyntaxError, OSError):
        return ModuleInfo(rel_path=rel, docstring="[SYNTAX ERROR]")

    classes: list[str] = []
    functions: list[str] = []

    for node in ast.iter_child_nodes(tree):
        if isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
            classes.append(node.name)
        elif isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
            if not node.name.startswith("_"):
                functions.append(node.name)

    raw_doc = ast.get_docstring(tree) or ""
    doc = raw_doc.splitlines()[0].strip() if raw_doc else ""

    return ModuleInfo(rel_path=rel, classes=classes, public_functions=functions, docstring=doc)


def scan_python_sources(target_dir: Path) -> list[ModuleInfo]:
    """Scan all .py files under *target_dir* via AST.

    Returns a sorted list of ModuleInfo (pure function — reads files, but
    performs no writes or network calls in the scan loop).

    File discovery uses :func:`~zenzic.core.discovery.walk_files` with a
    :class:`~zenzic.core.exclusion.LayeredExclusionManager` so that
    ``SYSTEM_EXCLUDED_DIRS`` (build artefacts, VCS, virtual-envs, caches)
    are pruned at the directory level — never entered at all.  This is
    identical to the view the Sentinel linter has during ``check all``
    (CEO-283 Unified Vision Sweep).

    Excludes:
      - ``__init__.py`` — no public API surface to document
      - ``tests/`` and ``test/`` directories — excluded via the manager
      - All ``SYSTEM_EXCLUDED_DIRS`` — pruned by :func:`walk_files`
    """
    # Lazy imports — keep module importable without the full Zenzic stack.
    from zenzic.core.discovery import walk_files
    from zenzic.core.exclusion import LayeredExclusionManager
    from zenzic.models.config import ZenzicConfig

    config = ZenzicConfig()
    manager = LayeredExclusionManager(
        config,
        repo_root=target_dir,
        # Prune test directories at walk level — they are not part of the
        # public module surface that brain map documents.
        cli_exclude=["tests", "test"],
    )
    filtered = sorted(
        f
        for f in walk_files(target_dir, frozenset(), manager)
        if f.suffix == ".py" and f.name != "__init__.py"
    )
    return [_extract_info(p, target_dir) for p in filtered]


def render_markdown_table(modules: list[ModuleInfo]) -> str:
    """Render a Markdown table from a list of ModuleInfo.

    Returns the full [CODE MAP] content block (without MAP_START/MAP_END markers).
    Pure function — no I/O.
    """
    lines = [
        "### Module Quick Index",
        "",
        "> Auto-generated by `zenzic brain map` via AST (CEO-242 — Sovereign Cartographer).",
        "> Update with `just brain-map` after any change to `src/`.",
        "",
        "| File | Classes | Public Functions | Note |",
        "|------|---------|-----------------|------|",
    ]
    for mod in modules:
        classes_str = ", ".join(f"`{c}`" for c in mod.classes) or "—"
        funcs_str = ", ".join(f"`{f}`" for f in mod.public_functions) or "—"
        note = mod.docstring or "[⚠️ UNDOCUMENTED]"
        lines.append(f"| `{mod.rel_path}` | {classes_str} | {funcs_str} | {note} |")

    return "\n".join(lines)


def update_ledger(ledger_path: Path, map_block: str) -> bool:
    """Replace the content between MAP_START and MAP_END in ledger_path.

    Returns True if the ledger was updated, False if the content was already
    identical (idempotent — safe to call on every save).

    Raises ValueError if the MAP_START / MAP_END markers are not found.
    """
    text = ledger_path.read_text(encoding="utf-8")
    start_idx = text.find(MAP_START)
    end_idx = text.find(MAP_END)

    if start_idx == -1 or end_idx == -1:
        raise ValueError(
            f"Markers {MAP_START!r} or {MAP_END!r} not found in {ledger_path}. "
            "Add the markers to ZENZIC_BRAIN.md before running 'zenzic brain map'."
        )

    new_block = f"{MAP_START}\n{map_block}\n{MAP_END}"
    new_text = text[:start_idx] + new_block + text[end_idx + len(MAP_END) :]

    if new_text == text:
        return False  # already up to date — skip write

    ledger_path.write_text(new_text, encoding="utf-8")
    return True


def load_dev_gate(repo_root: Path) -> list[str]:
    """Load forbidden patterns from ``.zenzic.dev.toml`` in *repo_root*.

    Returns the list of strings declared under
    ``[development_gate].forbidden_patterns``.  If the file is absent, the
    section is missing, or the key is missing, returns an empty list — the
    gate is silently disabled (zero-noise default).

    Pure at the decision layer — all I/O is isolated in this function.
    """
    dev_toml = repo_root / ".zenzic.dev.toml"
    if not dev_toml.exists():
        return []
    try:
        data = tomllib.loads(dev_toml.read_text(encoding="utf-8"))
    except (tomllib.TOMLDecodeError, OSError):
        return []
    raw = data.get("development_gate", {}).get("forbidden_patterns", [])
    return [str(p) for p in raw] if isinstance(raw, list) else []


def check_perimeter(text: str, forbidden: list[str]) -> list[str]:
    """Check *text* for any of the *forbidden* **literal** strings.

    Matching is **case-insensitive** (CEO-265): both *text* and each
    pattern are normalised to lower-case before the ``in`` check.
    Patterns are matched verbatim — regular expressions are not
    supported (CEO-276 Literal Certainty Standard).

    Returns the list of violated patterns in their original case as declared
    in ``.zenzic.dev.toml``.  Pure function — no I/O, no side effects.
    """
    normalised = text.lower()
    return [p for p in forbidden if p.lower() in normalised]


def redact_perimeter(text: str, forbidden: list[str]) -> str:
    """Replace all occurrences of *forbidden* **literal** strings with
    ``[REDACTED_BY_SENTINEL]`` in *text*.

    Matching is **case-insensitive** (CEO-265).  Uses ``re.escape`` so
    that path separators, dots, and other special characters in patterns
    are treated as literal text — no regex interpretation risk (CEO-276
    Literal Certainty Standard / ReDoS safety).

    Pure function — no I/O, no side effects.
    """
    result = text
    for pattern in forbidden:
        result = re.sub(
            re.escape(pattern),
            "[REDACTED_BY_SENTINEL]",
            result,
            flags=re.IGNORECASE,
        )
    return result


def render_json(modules: list[ModuleInfo]) -> str:
    """Render *modules* as a machine-readable JSON string.

    The output is a JSON array where each element corresponds to one
    ``ModuleInfo`` with keys ``rel_path``, ``classes``, ``public_functions``,
    and ``docstring``.  Sorted deterministically — the input list is already
    sorted by ``scan_python_sources``.  Pure function — no I/O.
    """
    return json.dumps([dataclasses.asdict(m) for m in modules], indent=2)


#: File extensions scanned by D002 Phase B (CEO-269/281).
#: Discovery is VCS-aware via LayeredExclusionManager (CEO-281 Universal Discovery Enforcement).
_D002_EXTENSIONS: frozenset[str] = frozenset({".py", ".md", ".mdx", ".toml", ".yml"})


def check_sources_perimeter(
    scan_root: Path,
    forbidden: list[str],
    *,
    exclude: frozenset[Path] | None = None,
) -> list[tuple[str, str]]:
    """Scan **raw text** of every tracked source file under *scan_root*.

    Uses :func:`~zenzic.core.discovery.walk_files` together with a
    :class:`~zenzic.core.exclusion.LayeredExclusionManager` so that file
    enumeration is **VCS-aware** and respects ``SYSTEM_EXCLUDED_DIRS``
    (CEO-281 Universal Discovery Enforcement).  ``glob`` and ``rglob`` are
    explicitly forbidden — all discovery goes through the official pipeline.

    File types scanned: ``.py``, ``.md``, ``.mdx``, ``.toml``, ``.yml``
    (CEO-269 Absolute Perimeter).

    Parameters
    ----------
    scan_root:
        Root directory to scan recursively (typically ``repo_root``).
    forbidden:
        List of literal strings (case-insensitive) to detect.
    exclude:
        Optional set of **resolved** ``Path`` objects permanently immune from
        the scan.  CEO-278 Sovereign Immunity: ``.zenzic.dev.toml`` must
        always be passed here by ``brain_map`` — the config file contains the
        forbidden patterns themselves and must never arrest itself.

    Returns a sorted list of ``(rel_path, pattern)`` tuples — one entry per
    (file × violated-pattern) pair.  Pure except for file reads.  Does not
    raise — unreadable files are silently skipped (OSError).
    """
    # Lazy imports keep cartography.py light for callers that only use AST
    # scanning, while satisfying Rule R02 (Mandatory ExclusionManager).
    from zenzic.core.discovery import walk_files
    from zenzic.core.exclusion import LayeredExclusionManager
    from zenzic.models.config import ZenzicConfig

    _exclude = exclude or frozenset()
    # Minimal config: SYSTEM_EXCLUDED_DIRS are active by default via
    # model_post_init.  No project-specific exclusions — D002 must scan
    # the full repo surface, not a documentation subset.
    config = ZenzicConfig()
    manager = LayeredExclusionManager(config, repo_root=scan_root)

    violations: list[tuple[str, str]] = []
    for f in walk_files(scan_root, frozenset(), manager):
        if f.suffix not in _D002_EXTENSIONS:
            continue
        # CEO-278: Sovereign Immunity — skip the gate config file itself.
        if f.resolve() in _exclude:
            continue
        try:
            raw = f.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        hits = check_perimeter(raw, forbidden)
        try:
            rel = str(f.relative_to(scan_root))
        except ValueError:
            continue
        for p in hits:
            violations.append((rel, p))
    return sorted(violations)
