# SPDX-FileCopyrightText: 2026 PythonWoods <dev@pythonwoods.dev>
# SPDX-License-Identifier: Apache-2.0
"""Zenzic Finding Code Registry.

Every finding Zenzic emits carries a stable machine-readable code of the form
``Zxxx``.  This module is the single source of truth for code assignments.

Schema
------
Z0xx — Migration & Compatibility
    Z000  UNSUPPORTED_ENGINE   — unsupported/removed engine identifier; ConfigurationError before analysis

Z1xx — Link Integrity
    Z101  LINK_BROKEN          — target file not found in the Virtual Site Map
    Z102  ANCHOR_MISSING       — fragment target (#anchor) not defined on the page
    Z103  ORPHAN_LINK          — link target exists but is not in the nav (ORPHAN_BUT_EXISTING)
    Z104  FILE_NOT_FOUND       — link target file missing from the filesystem
    Z105  ABSOLUTE_PATH        — link uses an absolute path (not portable)
    Z106  CIRCULAR_LINK        — link is part of a circular reference cycle (info)
    Z107  CIRCULAR_ANCHOR      — anchor link whose text slugifies to its own fragment
    Z108  EMPTY_LINK_TEXT      — link label is empty or whitespace-only
    Z109  EXTERNAL_LINK_BROKEN — external URL returned an HTTP error or could not be reached
    Z111  VIRTUAL_ROUTE_BROKEN — link targets a virtual route that was never generated by any frontmatter
    Z112  <reserved>
    Z113  AUTHOR_KEY_COLLISION — duplicate author key across blog author configs
    Z114  LARGE_PAGINATION_SET — blog pagination set exceeds 200-page threshold (info)

Z2xx — Security (Credential Scanner)
    Z201  CREDENTIAL_SECRET    — credential / secret detected (Exit 2)
    Z202  PATH_TRAVERSAL       — path escapes the docs root boundary
    Z203  PATH_TRAVERSAL_FATAL — traversal targeting OS system directories (Exit 3)
    Z204  FORBIDDEN_TERM       — project-specific forbidden term in documentation content (Exit 2)

Z3xx — Reference Integrity
    Z301  DANGLING_REF         — reference link uses an undefined ID
    Z302  DEAD_DEF             — reference definition never used by any link
    Z303  DUPLICATE_DEF        — reference ID defined more than once

Z4xx — Structure
    Z401  MISSING_DIRECTORY_INDEX — directory lacks an index page (Standalone Mode)
    Z402  ORPHAN_PAGE          — Markdown file not listed in the site navigation
    Z403  MISSING_ALT          — image element has no alt text
    Z404  CONFIG_ASSET_MISSING — infrastructure asset referenced in engine config not found on disk
     Z405  UNUSED_ASSET         — asset file not referenced by any documentation page
     Z406  NAV_CONTRACT         — navigation contract violation

Z5xx — Content Quality
    Z501  PLACEHOLDER          — page contains stub / TODO content
    Z502  SHORT_CONTENT        — page word count below minimum threshold
    Z503  SNIPPET_ERROR        — fenced code block fails syntax validation
    Z504  QUALITY_REGRESSION   — quality scorer detected score drop vs saved baseline
    Z505  UNTAGGED_CODE_BLOCK  — fenced code block has no language specifier
    Z506  MALFORMED_FRONTMATTER — frontmatter opening delimiter is malformed (e.g., '--' instead of '---')

Z6xx — Governance (opt-in)
     Z601  BRAND_OBSOLESCENCE   — deprecated brand term found in documentation source
     Z602  I18N_PARITY          — [INACTIVE] bilingual parity deferred to future adapter plugins; not enforced in v0.14.0

Z9xx — Engine / System
    Z901  RULE_ENGINE_ERROR    — plugin rule raised an unexpected exception
    Z902  RULE_TIMEOUT         — plugin rule exceeded the per-file time limit (ReDoS guard)
    Z906  NO_FILES_FOUND       — target directory contains no Markdown sources (audit skipped)
"""

from __future__ import annotations

from typing import NamedTuple


# ── Code Definition — Single Source of Truth ─────────────────────────────────


class CodeDefinition(NamedTuple):
    """Per-code scoring and CI gate metadata — Single Source of Truth (ADR-031).

    All three attributes are defined **once** here; ``scorer.py`` derives its
    penalty/category tables and ``_check.py`` derives finding severity from this
    structure.  No catch-all ``else 'error'`` logic is permitted elsewhere.

    Attributes:
        severity: SARIF ``defaultConfiguration.level`` — ``"error"``,
            ``"warning"``, or ``"note"``.
        penalty:  Points deducted from the category bucket per occurrence.
            ``0.0`` for codes that are informational or handled by a dedicated
            gate (Security Override, Governance Gate).
        category: DQS bucket — ``"structural"``, ``"navigation"``,
            ``"content"``, ``"brand"``, or ``None`` for codes outside the
            penalty table.
        status:   Lifecycle state — ``"active"`` (default) or ``"inactive"``
            for codes whose scanner logic has been deferred or removed.
            Inactive codes remain in the namespace for config compatibility
            but are never emitted by the engine.
    """

    severity: str
    penalty: float
    category: str | None
    status: str = "active"


# ── Exit Code Contract ────────────────────────────────────────────────────────


class ZenzicExitCode:
    """Centralised exit code constants for the Zenzic CLI.

    These values implement the Exit Code Contract:

    * ``SUCCESS`` (0) — all checks passed; documentation is clean.
    * ``QUALITY`` (1) — quality findings (broken links, orphans, …);
      suppressible by ``--exit-zero``.
    * ``CREDENTIAL_LEAK`` (2) — credential detected (Z201);
      **never** suppressible.
    * ``PATH_TRAVERSAL_FATAL`` (3) — system path traversal (Z202/Z203);
      **never** suppressible.

    Usage in CLI layer::

        from zenzic.core.codes import ZenzicExitCode
        raise typer.Exit(ZenzicExitCode.CREDENTIAL_LEAK)
    """

    SUCCESS: int = 0
    QUALITY: int = 1
    CREDENTIAL_LEAK: int = 2
    PATH_TRAVERSAL_FATAL: int = 3


# ── Stability Contract ────────────────────────────────────────────────────────

FROZEN_CODES: frozenset[str] = frozenset(
    {
        "Z000",
        "Z201",
        "Z202",
        "Z203",
        "Z204",
        "Z405",
        "Z406",
        "Z601",
    }
)

NON_SUPPRESSIBLE_CODES: frozenset[str] = frozenset(
    {
        "Z201",
        "Z202",
        "Z203",
        "Z204",
    }
)

PLUGIN_FORBIDDEN_EXITS: frozenset[int] = frozenset({2, 3})


# ── Code Definitions (SSoT) ───────────────────────────────────────────────────
# Every Zxxx code is defined ONCE here with its severity, DQS penalty, and
# scoring category.  scorer.py and _check.py derive their tables from this dict.
# Adding a new code requires a single entry here — nowhere else.

CODE_DEFINITIONS: dict[str, CodeDefinition] = {
    # ── Z0xx — Migration & Compatibility ──────────────────────────────────────
    # Aborts config loading before any analysis; not in the DQS penalty table.
    "Z000": CodeDefinition("error", 0.0, None),
    # ── Z1xx — Link Integrity ─────────────────────────────────────────────────
    "Z101": CodeDefinition("error", 8.0, "structural"),  # LINK_BROKEN
    "Z102": CodeDefinition("error", 5.0, "structural"),  # ANCHOR_MISSING
    "Z103": CodeDefinition(
        "error", 2.0, "structural"
    ),  # ORPHAN_LINK      — ADR-031 paradox resolved
    "Z104": CodeDefinition("error", 8.0, "structural"),  # FILE_NOT_FOUND
    "Z105": CodeDefinition("error", 2.0, "structural"),  # ABSOLUTE_PATH
    "Z106": CodeDefinition("note", 0.0, None),  # CIRCULAR_LINK    — informational
    "Z107": CodeDefinition("error", 1.0, "structural"),  # CIRCULAR_ANCHOR
    "Z108": CodeDefinition("error", 1.0, "structural"),  # EMPTY_LINK_TEXT
    "Z109": CodeDefinition("error", 3.0, "structural"),  # EXTERNAL_LINK_BROKEN
    "Z111": CodeDefinition(
        "error", 8.0, "structural"
    ),  # VIRTUAL_ROUTE_BROKEN — ADR-031 paradox resolved
    "Z113": CodeDefinition(
        "error", 2.0, "structural"
    ),  # AUTHOR_KEY_COLLISION — ADR-031 paradox resolved
    "Z114": CodeDefinition("note", 0.0, None),  # LARGE_PAGINATION_SET — informational threshold
    # ── Z2xx — Security ───────────────────────────────────────────────────────
    # Score collapses to 0 via Security Override; never in DQS category bucket.
    # Exit codes 2–3; non-suppressible (see NON_SUPPRESSIBLE_CODES).
    "Z201": CodeDefinition("error", 0.0, None),  # CREDENTIAL_SECRET
    "Z202": CodeDefinition("error", 0.0, None),  # PATH_TRAVERSAL
    "Z203": CodeDefinition("error", 0.0, None),  # PATH_TRAVERSAL_FATAL
    "Z204": CodeDefinition("error", 0.0, None),  # FORBIDDEN_TERM
    # ── Z3xx — Reference Integrity ────────────────────────────────────────────
    "Z301": CodeDefinition("warning", 4.0, "navigation"),  # DANGLING_REF
    "Z302": CodeDefinition("warning", 1.0, "navigation"),  # DEAD_DEF
    "Z303": CodeDefinition("warning", 3.0, "navigation"),  # DUPLICATE_DEF
    # ── Z4xx — Structure ──────────────────────────────────────────────────────
    "Z401": CodeDefinition(
        "note", 0.0, "navigation"
    ),  # MISSING_DIRECTORY_INDEX — info only, no DQS penalty
    "Z402": CodeDefinition("warning", 4.0, "navigation"),  # ORPHAN_PAGE
    "Z403": CodeDefinition("warning", 1.0, "content"),  # MISSING_ALT
    "Z404": CodeDefinition("warning", 3.0, "brand"),  # CONFIG_ASSET_MISSING
    "Z405": CodeDefinition("warning", 3.0, "brand"),  # UNUSED_ASSET
    "Z406": CodeDefinition("warning", 2.0, "brand"),  # NAV_CONTRACT
    # ── Z5xx — Content Quality ────────────────────────────────────────────────
    "Z501": CodeDefinition("warning", 2.0, "content"),  # PLACEHOLDER
    "Z502": CodeDefinition("warning", 1.0, "content"),  # SHORT_CONTENT
    "Z503": CodeDefinition("warning", 10.0, "content"),  # SNIPPET_ERROR
    "Z504": CodeDefinition("warning", 0.0, None),  # QUALITY_REGRESSION — governance gate
    "Z505": CodeDefinition("warning", 1.0, "content"),  # UNTAGGED_CODE_BLOCK
    "Z506": CodeDefinition("error", 5.0, "content"),  # MALFORMED_FRONTMATTER
    # ── Z6xx — Governance ─────────────────────────────────────────────────────
    "Z601": CodeDefinition("warning", 2.0, "brand"),  # BRAND_OBSOLESCENCE (escalates exponentially)
    "Z602": CodeDefinition(
        "warning", 0.0, None, "inactive"
    ),  # I18N_PARITY — INACTIVE; deferred to future adapter plugins
    # ── Z9xx — Engine / System ────────────────────────────────────────────────
    "Z901": CodeDefinition("warning", 0.0, None),  # RULE_ENGINE_ERROR
    "Z902": CodeDefinition("warning", 0.0, None),  # RULE_TIMEOUT
    "Z906": CodeDefinition("note", 0.0, None),  # NO_FILES_FOUND — informational
}


#: Human-readable name for each code (for report headers).
CODE_NAMES: dict[str, str] = {
    "Z000": "UNSUPPORTED_ENGINE",
    "Z101": "LINK_BROKEN",
    "Z102": "ANCHOR_MISSING",
    "Z103": "ORPHAN_LINK",
    "Z104": "FILE_NOT_FOUND",
    "Z105": "ABSOLUTE_PATH",
    "Z106": "CIRCULAR_LINK",
    "Z107": "CIRCULAR_ANCHOR",
    "Z108": "EMPTY_LINK_TEXT",
    "Z109": "EXTERNAL_LINK_BROKEN",
    "Z111": "VIRTUAL_ROUTE_BROKEN",
    "Z113": "AUTHOR_KEY_COLLISION",
    "Z114": "LARGE_PAGINATION_SET",
    "Z201": "CREDENTIAL_SECRET",
    "Z202": "PATH_TRAVERSAL",
    "Z203": "PATH_TRAVERSAL_FATAL",
    "Z204": "FORBIDDEN_TERM",
    "Z301": "DANGLING_REF",
    "Z302": "DEAD_DEF",
    "Z303": "DUPLICATE_DEF",
    "Z401": "MISSING_DIRECTORY_INDEX",
    "Z402": "ORPHAN_PAGE",
    "Z403": "MISSING_ALT",
    "Z404": "CONFIG_ASSET_MISSING",
    "Z405": "UNUSED_ASSET",
    "Z406": "NAV_CONTRACT",
    "Z501": "PLACEHOLDER",
    "Z502": "SHORT_CONTENT",
    "Z503": "SNIPPET_ERROR",
    "Z504": "QUALITY_REGRESSION",
    "Z505": "UNTAGGED_CODE_BLOCK",
    "Z506": "MALFORMED_FRONTMATTER",
    "Z601": "BRAND_OBSOLESCENCE",
    "Z602": "I18N_PARITY",  # inactive
    "Z901": "RULE_ENGINE_ERROR",
    "Z902": "RULE_TIMEOUT",
    "Z906": "NO_FILES_FOUND",
}

#: Short description of each code for SARIF ``shortDescription`` and human display.
#: Single source of truth — never duplicate these strings in other modules.
CODE_DESCRIPTIONS: dict[str, str] = {
    # Z0xx — Migration & Compatibility
    "Z000": "Unsupported or removed engine identifier in .zenzic.toml — configuration guard raised before analysis begins",
    # Z1xx — Link Integrity
    "Z101": "Link target not found in the Virtual Site Map",
    "Z102": "Fragment anchor (#anchor) not defined on the target page",
    "Z103": "Link target exists but is not reachable via site navigation",
    "Z104": "Link target file missing from the filesystem",
    "Z105": "Absolute path detected — use a relative path for portability",
    "Z106": "Circular link chain detected between documentation pages",
    "Z107": "Self-referential anchor link — slug(text) resolves to the same fragment",
    "Z108": "Link label is empty or contains only whitespace",
    "Z109": "External URL returned an HTTP error or could not be reached",
    "Z111": "Link targets a virtual route (tag page, paginated index, author profile) that was never generated by any frontmatter",
    "Z113": "Duplicate author key declared across two or more blog author config files",
    "Z114": "Blog pagination set exceeds the 200-page informational threshold",
    # Z2xx — Security
    "Z201": "Potential credential or secret detected in documentation content",
    "Z202": "Link escapes the documentation root boundary (path traversal)",
    "Z203": "Path traversal targeting OS system directories — fatal security breach",
    "Z204": "Forbidden project term detected in documentation content",
    # Z3xx — Reference Integrity
    "Z301": "Reference-style link uses an undefined identifier",
    "Z302": "Link definition declared but never referenced",
    "Z303": "Reference identifier defined more than once",
    # Z4xx — Structure
    "Z401": "Directory lacks a required index page",
    "Z402": "Markdown file not listed in the site navigation",
    "Z403": "Image element has no alt text",
    "Z404": "Asset referenced in engine config not found on disk",
    "Z405": "Asset file not referenced by any documentation page",
    "Z406": "Navigation contract violation detected",
    # Z5xx — Content Quality
    "Z501": "Page contains placeholder or stub content",
    "Z502": "Page word count is below the minimum threshold",
    "Z503": "Fenced code block contains a syntax error",
    "Z504": "Documentation quality score regressed below the saved baseline",
    "Z505": "Fenced code block has no language specifier",
    "Z506": "Frontmatter boundary is malformed (e.g., opening delimiter is '--' instead of '---')",
    # Z6xx — Governance
    "Z601": "Deprecated brand term found in documentation source",
    "Z602": "[INACTIVE] Bilingual parity deferred to future adapter plugins — not enforced in v0.14.0",
    # Z9xx — Engine / System
    "Z901": "Plugin rule raised an unexpected exception",
    "Z902": "Plugin rule exceeded the per-file time limit (ReDoS guard)",
    "Z906": "Target directory contains no Markdown sources — audit skipped",
}

#: Default SARIF ``defaultConfiguration.level`` for each code.
#: Derived from :data:`CODE_DEFINITIONS` — do not edit manually.
#: Individual Finding severity always takes precedence at result level.
CODE_SARIF_LEVELS: dict[str, str] = {code: defn.severity for code, defn in CODE_DEFINITIONS.items()}


def get_sarif_name(code: str) -> str:
    """Convert a Zxxx code to its SARIF-canonical CamelCase rule name.

    Derives the name deterministically from :data:`CODE_NAMES`:
    ``"LINK_BROKEN"`` → ``"LinkBroken"``.  Falls back to the raw code
    string for unknown codes so the SARIF remains valid even for
    dynamically emitted plugin codes.

    Args:
        code: A canonical Zxxx code string, e.g. ``"Z101"``.

    Returns:
        CamelCase rule name suitable for the SARIF ``rules[].name`` field.
    """
    name = CODE_NAMES.get(code, code)
    return "".join(word.capitalize() for word in name.split("_"))


# ── Core Scanner Registry ─────────────────────────────────────────────────────


class CoreScanner(NamedTuple):
    """Static descriptor for a built-in Zenzic scanner.

    These scanners are compiled into Zenzic itself — always active, not
    configurable or removable via the ``zenzic.rules`` entry-point group.
    """

    codes: str
    """Display code range, e.g. ``"Z201"`` or ``"Z202\u2013203"``."""

    name: str
    """Human-readable scanner name, e.g. ``"Credential Scanner"``."""

    capability: str
    """One-line capability summary shown in ``zenzic inspect capabilities``."""

    primary_exit: int
    """Primary exit code: 1 (quality), 2 (credential leak), or 3 (path traversal)."""

    non_suppressible: bool
    """``True`` when ``--exit-zero`` cannot override this scanner's exit."""


#: Built-in scanners — static, always active, single source of truth for
#: ``zenzic inspect capabilities`` and any future Arsenal introspection.
CORE_SCANNERS: list[CoreScanner] = [
    CoreScanner(
        codes="Z201",
        name="Credential Scanner",
        capability=(
            "Credential & secret detection \u2014 9 families "
            "(AWS, GitHub, GitLab PAT, Stripe, Slack, OpenAI, Google, PEM, hex)"
        ),
        primary_exit=2,
        non_suppressible=True,
    ),
    CoreScanner(
        codes="Z204",
        name="Privacy Gate",
        capability=(
            "Project-specific forbidden term detection \u2014 "
            "verbatim case-insensitive match against patterns in .zenzic.local.toml"
        ),
        primary_exit=2,
        non_suppressible=True,
    ),
    CoreScanner(
        codes="Z202\u2013203",
        name="Path Traversal Guard",
        capability=(
            "Path-traversal boundary enforcement \u2014 rejects any link escaping the docs/ root"
        ),
        primary_exit=3,
        non_suppressible=True,
    ),
    CoreScanner(
        codes="Z101–106, Z108–109",
        name="Link Validator",
        capability=(
            "Broken links, dead anchors, circular refs, "
            "absolute internal links, empty link text, external URL validation"
        ),
        primary_exit=1,
        non_suppressible=False,
    ),
    CoreScanner(
        codes="Z301\u2013303",
        name="Reference Scanner",
        capability="Dangling reference IDs, dead link definitions, duplicate reference keys",
        primary_exit=1,
        non_suppressible=False,
    ),
    CoreScanner(
        codes="Z401\u2013404",
        name="Structure Guard",
        capability=(
            "Directory-index integrity, orphan pages, missing alt text, config asset paths"
        ),
        primary_exit=1,
        non_suppressible=False,
    ),
    CoreScanner(
        codes="Z501\u2013503, Z506",
        name="Content Guard",
        capability=(
            "Placeholder / stub text, overly short pages, syntax errors in code snippets, "
            "malformed frontmatter delimiters"
        ),
        primary_exit=1,
        non_suppressible=False,
    ),
    CoreScanner(
        codes="Z405",
        name="Asset Sentry",
        capability="Unused images and media files not referenced anywhere in the docs tree",
        primary_exit=1,
        non_suppressible=False,
    ),
    CoreScanner(
        codes="Z406",
        name="Nav Contract Enforcer",
        capability="Navigation contract violation — page presence against declared nav structure",
        primary_exit=1,
        non_suppressible=False,
    ),
    CoreScanner(
        codes="Z111, Z113–114",
        name="Blog Integrity Guard",
        capability=(
            "Zensical blog integrity — virtual route resolution (tag/author/paginated), "
            "duplicate author keys, large pagination set threshold"
        ),
        primary_exit=1,
        non_suppressible=False,
    ),
    CoreScanner(
        codes="Z107",
        name="Circular Anchor Guard",
        capability=(
            "Self-referential anchor links \u2014 detects [text](#fragment) "
            "where slug(text) == fragment"
        ),
        primary_exit=1,
        non_suppressible=False,
    ),
    CoreScanner(
        codes="Z505",
        name="Code Block Scanner",
        capability="Fenced code blocks without a language specifier (``` or ~~~)",
        primary_exit=1,
        non_suppressible=False,
    ),
    CoreScanner(
        codes="Z601",
        name="Brand Integrity Guard",
        capability=(
            "Deprecated brand term detection \u2014 configurable via [governance], "
            "suppressed per-line with <!-- zenzic:ignore: Z601 --> (Markdown) or {/* zenzic:ignore: Z601 */} (MDX)"
        ),
        primary_exit=1,
        non_suppressible=False,
    ),
]


def label(code: str) -> str:
    """Return ``"Zxxx NAME"`` for display, e.g. ``"Z101 LINK_BROKEN"``.

    Falls back to just the code when no name is registered.
    """
    name = CODE_NAMES.get(code, "")
    return f"{code} {name}".strip()
