# SPDX-FileCopyrightText: 2026 PythonWoods <dev@pythonwoods.dev>
# SPDX-License-Identifier: Apache-2.0
"""Base adapter contract for all documentation engines.

ADR-078-STRICT hardens the adapter API from structural Protocol typing to a
runtime-enforced ABC contract. Every first-party and third-party adapter must
subclass :class:`BaseAdapter`.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Literal


if TYPE_CHECKING:
    from zenzic.models.vsm import RouteStatus


# ── Route metadata types ─────────────────────────────────────────────────────


VirtualRouteKind = Literal["tag", "tag_index", "pagination", "author", "author_index"]


@dataclass(frozen=True, slots=True)
class VirtualRoute:
    """A route generated by the build engine without a physical markdown file."""

    url: str
    label: str
    source_files: frozenset[str]
    kind: VirtualRouteKind

    def __post_init__(self) -> None:
        if not self.source_files:
            raise ValueError(
                f"VirtualRoute {self.url!r}: source_files is empty — "
                "Reverse-Mapping Invariant violated"
            )


@dataclass(slots=True)
class RouteMetadata:
    """Unified route information for one source file."""

    canonical_url: str
    status: RouteStatus
    slug: str | None = None
    route_base_path: str = "/"
    is_proxy: bool = False
    version: str | None = None


# ── Adapter contract ─────────────────────────────────────────────────────────


class BaseAdapter(ABC):
    """Runtime-enforced adapter contract used by scanner, validator, and VSM."""

    @abstractmethod
    def is_locale_dir(self, part: str) -> bool:
        """Return ``True`` when *part* is a non-default locale directory name."""

    @abstractmethod
    def resolve_asset(self, missing_abs: Path, docs_root: Path) -> Path | None:
        """Return default-locale fallback for a missing asset, else ``None``."""

    @abstractmethod
    def resolve_anchor(
        self,
        resolved_file: Path,
        anchor: str,
        anchors_cache: dict[Path, set[str]],
        docs_root: Path,
    ) -> bool:
        """Return ``True`` when an anchor miss should be suppressed via i18n fallback."""

    @abstractmethod
    def is_shadow_of_nav_page(self, rel: Path, nav_paths: frozenset[str]) -> bool:
        """Return ``True`` when *rel* mirrors a nav-listed default-locale page."""

    @abstractmethod
    def get_ignored_patterns(self) -> set[str]:
        """Return filename glob patterns ignored by orphan detection."""

    @abstractmethod
    def get_nav_paths(self) -> frozenset[str]:
        """Return nav-listed markdown paths relative to ``docs_root``."""

    @abstractmethod
    def has_engine_config(self) -> bool:
        """Return ``True`` when engine config exists and nav-based checks are meaningful."""

    @abstractmethod
    def get_metadata_files(self) -> frozenset[str]:
        """Return engine-owned config filenames excluded from quality findings."""

    @abstractmethod
    def get_route_info(self, rel: Path) -> RouteMetadata:
        """Return canonical URL and route status metadata for ``rel``."""

    def map_url(self, rel: Path) -> str:
        """Route mapping API backed by :meth:`get_route_info`."""
        return self.get_route_info(rel).canonical_url

    def classify_route(self, rel: Path, nav_paths: frozenset[str]) -> RouteStatus:  # noqa: ARG002
        """Route classification API backed by :meth:`get_route_info`."""
        return self.get_route_info(rel).status

    @abstractmethod
    def provides_index(self, directory_path: Path) -> bool:
        """Return whether the engine serves a landing page for ``directory_path``."""

    def get_link_scheme_bypasses(self) -> frozenset[str]:
        """Return URI schemes exempt from unknown-scheme and Z105 checks."""
        return frozenset()

    @abstractmethod
    def get_extra_content_roots(self, repo_root: Path) -> list[Path]:
        """Return additional markdown content roots outside ``docs_root``."""

    @abstractmethod
    def get_locale_source_roots(self, repo_root: Path) -> list[tuple[Path, str]]:
        """Return locale source roots as ``(root_path, locale_label)`` pairs."""

    @abstractmethod
    def get_absolute_url_prefixes(self, repo_root: Path | None = None) -> list[str]:  # noqa: ARG002
        """Return project-owned absolute URL prefixes (for Z105 allowlisting)."""
