# SPDX-FileCopyrightText: 2026 PythonWoods <dev@pythonwoods.dev>
# SPDX-License-Identifier: Apache-2.0
"""DocusaurusAdapter — adapter for Docusaurus v3 with native i18n support.

Docusaurus uses a fundamentally different geography from MkDocs:

- Source files live in ``docs/`` with ``.md`` or ``.mdx`` extensions.
- Translations live in ``i18n/{locale}/docusaurus-plugin-content-docs/current/``.
- The sidebar can be auto-generated from the filesystem or declared explicitly
  in ``sidebars.ts``.
- Frontmatter ``slug:`` overrides the canonical URL derived from the filepath.
- Clean URLs are the default: ``docs/guide/install.mdx`` → ``/docs/guide/install``.

Config parsing strategy (approved by Tech Lead):

- **Structural parameters** (locales, docs_dir, fallback) are read from
  ``zenzic.toml`` via ``BuildContext`` — same as ``ZensicalAdapter``.
- **``baseUrl``** is extracted from ``docusaurus.config.ts`` or ``.js`` via a
  minimal regex (no Node.js subprocess — Pillar 2 compliance).
- **Sidebar** in ``autogenerated`` mode: all files are ``REACHABLE``.

This module never imports or executes JavaScript.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import TYPE_CHECKING

from zenzic.core.adapters._utils import remap_to_default_locale
from zenzic.models.config import BuildContext


if TYPE_CHECKING:
    from zenzic.models.vsm import RouteStatus


# ── Config discovery ──────────────────────────────────────────────────────────


def find_docusaurus_config(repo_root: Path) -> Path | None:
    """Return the Docusaurus config file path, or ``None`` if absent.

    Checks for ``docusaurus.config.ts`` first (most common in Docusaurus v3),
    then falls back to ``docusaurus.config.js``.
    """
    for name in ("docusaurus.config.ts", "docusaurus.config.js"):
        candidate = repo_root / name
        if candidate.exists():
            return candidate
    return None


def _extract_base_url(config_path: Path) -> str:
    """Extract ``baseUrl`` from a Docusaurus config file via regex.

    Performs a minimal, surgical extraction without executing JavaScript.
    Falls back to ``'/'`` when the pattern is not found.

    Args:
        config_path: Path to ``docusaurus.config.ts`` or ``.js``.

    Returns:
        The ``baseUrl`` string (e.g. ``'/'`` or ``'/docs/'``).
    """
    try:
        content = config_path.read_text(encoding="utf-8")
    except OSError:
        return "/"
    # Match: baseUrl: '...' or baseUrl: "..."
    match = re.search(r"""baseUrl\s*:\s*['"]([^'"]+)['"]""", content)
    return match.group(1) if match else "/"


# ── Adapter ───────────────────────────────────────────────────────────────────


class DocusaurusAdapter:
    """Adapter for Docusaurus v3 documentation projects.

    Satisfies the :class:`~zenzic.core.adapters.BaseAdapter` protocol.

    Docusaurus geography:

    - Default locale docs: ``docs/`` (or custom ``docs_dir``).
    - Locale translations: ``i18n/{locale}/docusaurus-plugin-content-docs/current/``.
    - Both ``.md`` and ``.mdx`` extensions are valid source files.
    - Sidebar is typically auto-generated from the filesystem (all files
      ``REACHABLE``); explicit sidebar support is deferred to a future version.

    The adapter reads all structural metadata from ``BuildContext``
    (``zenzic.toml``).  Only ``baseUrl`` is extracted from the Docusaurus
    config file via minimal regex — no Node.js execution.

    Args:
        context: Build context from ``zenzic.toml``.
        docs_root: Resolved absolute path to the ``docs/`` directory.
        base_url: Docusaurus ``baseUrl`` (e.g. ``'/'``).
    """

    def __init__(
        self,
        context: BuildContext,
        docs_root: Path,
        base_url: str = "/",
    ) -> None:
        self._docs_root = docs_root
        self._base_url = base_url.rstrip("/") or ""

        # Locale configuration from BuildContext (zenzic.toml).
        self._locale_dirs: frozenset[str] = frozenset(context.locales)
        self._fallback_to_default: bool = context.fallback_to_default

        # Docusaurus i18n geography: translations live under
        # i18n/{locale}/docusaurus-plugin-content-docs/current/
        # When scanning, these are mapped into the docs tree as locale prefixes.
        self._i18n_prefix = "i18n"
        self._plugin_docs_segment = "docusaurus-plugin-content-docs/current"

    # ── BaseAdapter protocol ───────────────────────────────────────────────

    def is_locale_dir(self, part: str) -> bool:
        """Return ``True`` when *part* is a non-default locale directory name."""
        return part in self._locale_dirs

    def resolve_asset(self, missing_abs: Path, docs_root: Path) -> Path | None:
        """Return the default-locale fallback for a missing asset, or ``None``."""
        if not self._fallback_to_default:
            return None
        fallback = remap_to_default_locale(missing_abs, docs_root, self._locale_dirs)
        return fallback if fallback is not None and fallback.exists() else None

    def resolve_anchor(
        self,
        resolved_file: Path,
        anchor: str,
        anchors_cache: dict[Path, set[str]],
        docs_root: Path,
    ) -> bool:
        """Return ``True`` if an anchor miss should be suppressed via i18n fallback.

        Docusaurus serves the default-locale page when a translation does not
        exist.  If the anchor exists in the default-locale equivalent, the
        miss is spurious.
        """
        if not self._fallback_to_default:
            return False
        default_file = remap_to_default_locale(resolved_file, docs_root, self._locale_dirs)
        if default_file is None:
            return False
        return anchor.lower() in anchors_cache.get(default_file, set())

    def is_shadow_of_nav_page(self, rel: Path, nav_paths: frozenset[str]) -> bool:
        """Return ``True`` when *rel* is a locale-mirror of a nav-listed page.

        In Docusaurus auto-generated sidebar mode, all files are nav-listed,
        so locale mirrors are always shadows of a nav page.
        """
        default_abs = remap_to_default_locale(
            self._docs_root / rel, self._docs_root, self._locale_dirs
        )
        if default_abs is None:
            return False
        return default_abs.relative_to(self._docs_root).as_posix() in nav_paths

    def get_ignored_patterns(self) -> set[str]:
        """Return filename patterns Docusaurus ignores.

        Docusaurus ignores files and directories starting with ``_``
        (e.g. ``_category_.json``, ``_private/``).
        """
        return {"_*"}

    def get_nav_paths(self) -> frozenset[str]:
        """Return nav-listed paths.

        With auto-generated sidebar (the Docusaurus default), all ``.md`` and
        ``.mdx`` files are navigable.  This method returns an empty frozenset
        to signal "no explicit nav" — ``classify_route()`` treats all files as
        ``REACHABLE`` in that case (same semantics as MkDocs without nav).
        """
        return frozenset()

    def has_engine_config(self) -> bool:
        """``True`` — DocusaurusAdapter is constructed only when a config exists."""
        return True

    # ── VSM integration ────────────────────────────────────────────────────

    def map_url(self, rel: Path) -> str:
        """Map a physical source path to its Docusaurus canonical URL.

        Docusaurus URL rules:

        - Strip ``.md`` and ``.mdx`` extensions.
        - ``index.md(x)`` collapses to the parent directory URL.
        - Files prefixed with a numeric ordering (e.g. ``01-intro.mdx``) are
          served without the prefix **only** when ``_category_.json`` is
          present.  For safety, we preserve the full slug by default.

        Examples::

            guide/install.mdx   → /guide/install/
            guide/index.mdx     → /guide/
            index.mdx           → /
            checks.mdx          → /checks/

        Args:
            rel: Path of the source file relative to ``docs_root``.

        Returns:
            Canonical URL string with leading and trailing ``/``.
        """
        # Strip .md / .mdx extension
        stem = rel.with_suffix("")
        if stem.suffix == ".":
            # Handle edge case: file with no real stem after stripping
            stem = stem.with_suffix("")

        parts = list(stem.parts)
        if not parts:
            return "/"

        # index files collapse to their parent directory
        if parts[-1] == "index":
            parts = parts[:-1]

        if not parts:
            return "/"

        return "/" + "/".join(parts) + "/"

    def classify_route(self, rel: Path, nav_paths: frozenset[str]) -> RouteStatus:
        """Classify a Docusaurus route.

        Classification rules (priority order):

        1. ``IGNORED`` — any path segment starts with ``_`` (Docusaurus
           convention for private/meta files like ``_category_.json``).
        2. ``REACHABLE`` — when no explicit nav is declared (auto-generated
           sidebar mode), all non-ignored files are reachable.
        3. ``REACHABLE`` — when the file is listed in ``nav_paths`` or is a
           locale shadow of a nav-listed page.
        4. ``ORPHAN_BUT_EXISTING`` — file exists but not in sidebar.

        Ghost Routes: locale index pages (e.g. ``it/index.mdx``) are
        auto-generated by Docusaurus i18n and marked ``REACHABLE`` even
        when they don't appear in any explicit sidebar.

        Args:
            rel:       Source path relative to ``docs_root``.
            nav_paths: Nav-listed paths from ``get_nav_paths()``.

        Returns:
            ``RouteStatus`` literal (never ``'CONFLICT'``).
        """
        # Rule 1: Private/meta files starting with _
        if any(part.startswith("_") for part in rel.parts):
            return "IGNORED"

        # Draft files: check is deferred to frontmatter parsing (future).

        # Rule 2: No explicit nav → auto-generated sidebar → all REACHABLE
        if not nav_paths:
            return "REACHABLE"

        # Rule 3: Explicit nav match
        rel_posix = rel.as_posix()
        if rel_posix in nav_paths:
            return "REACHABLE"

        # Locale shadows inherit nav membership
        if self.is_shadow_of_nav_page(rel, nav_paths):
            return "REACHABLE"

        # Ghost Routes: locale entry points
        if rel.name in ("index.md", "index.mdx") and len(rel.parts) == 2:
            locale_dir = rel.parts[0]
            if locale_dir in self._locale_dirs:
                return "REACHABLE"

        # Rule 4: Not in nav
        return "ORPHAN_BUT_EXISTING"

    # ── Factory hook ───────────────────────────────────────────────────────

    @classmethod
    def from_repo(
        cls,
        context: BuildContext,
        docs_root: Path,
        repo_root: Path,
    ) -> DocusaurusAdapter:
        """Construct from a live repository root.

        Extracts ``baseUrl`` from ``docusaurus.config.ts`` (or ``.js``) via
        regex.  No Node.js execution — Pillar 2 compliance.

        Args:
            context: Build context from ``zenzic.toml``.
            docs_root: Resolved absolute ``docs/`` path.
            repo_root: Repository root (where ``docusaurus.config.*`` lives).

        Returns:
            Configured ``DocusaurusAdapter`` instance.
        """
        config_path = find_docusaurus_config(repo_root)
        base_url = _extract_base_url(config_path) if config_path else "/"
        return cls(context, docs_root, base_url)
