# SPDX-FileCopyrightText: 2026 PythonWoods <dev@pythonwoods.dev>
# SPDX-License-Identifier: Apache-2.0
"""DocusaurusAdapter — adapter for Docusaurus v3 with native i18n support.

Docusaurus uses a fundamentally different geography from MkDocs:

- Source files live in ``docs/`` with ``.md`` or ``.mdx`` extensions.
- Translations live in ``i18n/{locale}/docusaurus-plugin-content-docs/current/``.
- The sidebar can be auto-generated from the filesystem or declared explicitly
  in ``sidebars.ts``.
- Frontmatter ``slug:`` overrides the canonical URL derived from the filepath.
- Clean URLs are the default: ``docs/guide/install.mdx`` → ``/docs/guide/install``.

Config parsing strategy (approved by Tech Lead):

- **Structural parameters** (locales, docs_dir, fallback) are read from
  ``zenzic.toml`` via ``BuildContext`` — same as ``ZensicalAdapter``.
- **``baseUrl``** is extracted from ``docusaurus.config.ts`` or ``.js`` via a
  multi-pattern static parser (no Node.js subprocess — Pillar 2 compliance).
- **``routeBasePath``** is extracted from presets (e.g. ``@docusaurus/preset-classic``)
  when present.
- **``slug``** in frontmatter overrides the canonical URL in ``map_url()``.
- **Sidebar** in ``autogenerated`` mode: all files are ``REACHABLE``.

When the config uses dynamic patterns that defeat static analysis (async
functions, dynamic imports, template literals), the parser falls back to
``'/'`` with a warning — never crashes, never guesses.

This module never imports or executes JavaScript.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import TYPE_CHECKING

from zenzic.core.adapters._utils import case_sensitive_exists, remap_to_default_locale
from zenzic.models.config import BuildContext


if TYPE_CHECKING:
    from zenzic.core.adapters._base import RouteMetadata
    from zenzic.models.vsm import RouteStatus

_log = logging.getLogger(__name__)

# ── JS/TS comment stripping ──────────────────────────────────────────────────

# Matches single-line (//) and multi-line (/* */) comments, plus string
# literals (to avoid stripping comment-like text inside strings).
_COMMENT_RE = re.compile(
    r"//[^\n]*"  # single-line comment
    r"|/\*[\s\S]*?\*/"  # multi-line comment
    r'|"(?:[^"\\]|\\.)*"'  # double-quoted string (preserve)
    r"|'(?:[^'\\]|\\.)*'"  # single-quoted string (preserve)
    r"|`(?:[^`\\]|\\.)*`",  # template literal (preserve)
)


def _strip_js_comments(source: str) -> str:
    """Remove JS/TS comments while preserving string literals."""

    def _replacer(m: re.Match[str]) -> str:
        text = m.group()
        if text.startswith("//"):
            return ""
        if text.startswith("/*"):
            return ""
        return text  # string literal — keep

    return _COMMENT_RE.sub(_replacer, source)


# ── Dynamic config detection ────────────────────────────────────────────────

# Patterns that indicate the config is dynamically generated and cannot be
# reliably parsed statically.
_DYNAMIC_PATTERNS = (
    re.compile(r"export\s+default\s+async\b"),
    re.compile(r"module\.exports\s*=\s*async\b"),
    re.compile(r"export\s+default\s+function\b"),
    re.compile(r"module\.exports\s*=\s*function\b"),
    re.compile(r"\bimport\s*\("),  # dynamic import()
    re.compile(r"\brequire\s*\("),  # CommonJS dynamic require
)


def _is_dynamic_config(content: str) -> bool:
    """Return ``True`` when the config uses patterns that defeat static analysis."""
    return any(pat.search(content) for pat in _DYNAMIC_PATTERNS)


# ── Config discovery ──────────────────────────────────────────────────────────


def find_docusaurus_config(repo_root: Path) -> Path | None:
    """Return the Docusaurus config file path, or ``None`` if absent.

    Checks for ``docusaurus.config.ts`` first (most common in Docusaurus v3),
    then falls back to ``docusaurus.config.js``.
    """
    for name in ("docusaurus.config.ts", "docusaurus.config.js"):
        candidate = repo_root / name
        if candidate.exists():
            return candidate
    return None


# ── Static value extraction ──────────────────────────────────────────────────

# All patterns match the key in object-literal syntax:  key: 'value'
# or key: "value", with optional trailing comma and whitespace.

_BASE_URL_RE = re.compile(r"""baseUrl\s*:\s*['"]([^'"]+)['"]""")

_ROUTE_BASE_PATH_RE = re.compile(r"""routeBasePath\s*:\s*['"]([^'"]*?)['"]""")

# ── Infrastructure asset path extraction (Z404) ──────────────────────────────

# Matches: favicon: 'some/path' or favicon: "some/path"
_FAVICON_ASSET_RE = re.compile(r"""favicon\s*:\s*['"]([^'"]+)['"]""")

# Matches: image: 'path.png' — restricted to image extensions to avoid
# matching unrelated 'image:' keys (e.g. Docker image references).
_OG_IMAGE_ASSET_RE = re.compile(
    r"""(?<!\w)image\s*:\s*['"]([^'"]+\.(?:png|jpg|jpeg|svg|gif|webp))['"]"""
)


def _extract_base_url(config_path: Path) -> str:
    """Extract ``baseUrl`` from a Docusaurus config file via static analysis.

    Multi-pattern parser that handles:
    - ``export default { baseUrl: '...' }``
    - ``module.exports = { baseUrl: '...' }``
    - ``const config = { baseUrl: '...' }; export default config;``

    Falls back to ``'/'`` when:
    - The file cannot be read.
    - The config uses async functions or dynamic imports (with warning).
    - The ``baseUrl`` key is not found in any recognised pattern.

    Args:
        config_path: Path to ``docusaurus.config.ts`` or ``.js``.

    Returns:
        The ``baseUrl`` string (e.g. ``'/'`` or ``'/docs/'``).
    """
    try:
        raw = config_path.read_text(encoding="utf-8")
    except OSError:
        return "/"

    content = _strip_js_comments(raw)

    if _is_dynamic_config(content):
        _log.warning(
            "Docusaurus config at %s uses dynamic patterns (async/import()/require()); "
            "falling back to baseUrl='/' — declare baseUrl in zenzic.toml "
            "[build_context] to override.",
            config_path,
        )
        return "/"

    match = _BASE_URL_RE.search(content)
    return match.group(1) if match else "/"


def _extract_route_base_path(config_path: Path) -> str | None:
    """Extract ``routeBasePath`` from a Docusaurus config's preset/plugin block.

    Docusaurus presets (e.g. ``@docusaurus/preset-classic``) can override the
    docs URL prefix via ``docs.routeBasePath``.  When set to ``''``, docs are
    served at the site root instead of ``/docs/``.

    Returns ``None`` when ``routeBasePath`` is not found (caller should use
    the Docusaurus default ``'docs'``).

    Args:
        config_path: Path to ``docusaurus.config.ts`` or ``.js``.

    Returns:
        The ``routeBasePath`` string, or ``None`` when absent.
    """
    try:
        raw = config_path.read_text(encoding="utf-8")
    except OSError:
        return None

    content = _strip_js_comments(raw)

    if _is_dynamic_config(content):
        return None

    match = _ROUTE_BASE_PATH_RE.search(content)
    if match is None:
        return None
    return match.group(1)


def check_config_assets(config_path: Path, repo_root: Path) -> list[tuple[str, str]]:
    """Check that infrastructure assets referenced in ``docusaurus.config.*`` exist.

    Extracts ``favicon`` and ``themeConfig.image`` (OG/social-card) values via
    static analysis and verifies the physical files exist inside the Docusaurus
    ``static/`` directory.

    No subprocess execution.  Only two existence checks (one per asset class)
    — safe to call during discovery phase outside hot-path loops.

    Args:
        config_path: Path to ``docusaurus.config.ts`` or ``.js``.
        repo_root:   Repository root (parent of ``static/``).

    Returns:
        List of ``(rel_path, message)`` tuples for each missing asset.
        ``rel_path`` is relative to ``repo_root`` (e.g.
        ``"static/assets/favicon/png/icon.png"``).  Empty list when all
        referenced assets exist or the config cannot be parsed.
    """
    try:
        raw = config_path.read_text(encoding="utf-8")
    except OSError:
        return []

    content = _strip_js_comments(raw)
    static_root = repo_root / "static"
    issues: list[tuple[str, str]] = []

    # -- favicon ------------------------------------------------------------
    favicon_match = _FAVICON_ASSET_RE.search(content)
    if favicon_match:
        asset_rel = favicon_match.group(1).lstrip("/")
        if not (static_root / asset_rel).exists():
            issues.append(
                (
                    f"static/{asset_rel}",
                    f"favicon asset not found on disk: "
                    f"'static/{asset_rel}' "
                    f"(declared as favicon: '{favicon_match.group(1)}' "
                    f"in {config_path.name}) [Z404]",
                )
            )

    # -- OG / social-card image -------------------------------------------
    # Take the first image-extension match; the themeConfig.image field is
    # always the first occurrence in a well-structured config.
    og_match = _OG_IMAGE_ASSET_RE.search(content)
    if og_match:
        asset_rel = og_match.group(1).lstrip("/")
        if not (static_root / asset_rel).exists():
            issues.append(
                (
                    f"static/{asset_rel}",
                    f"OG/social-card image not found on disk: "
                    f"'static/{asset_rel}' "
                    f"(declared as image: '{og_match.group(1)}' "
                    f"in {config_path.name}) [Z404]",
                )
            )

    return issues


# ── Frontmatter slug extraction ──────────────────────────────────────────────

_FRONTMATTER_RE = re.compile(r"\A\s*---\s*\n(.*?)\n---", re.DOTALL)
_SLUG_RE = re.compile(r"^slug\s*:\s*['\"]?([^'\"#\n]+?)['\"]?\s*$", re.MULTILINE)


def _extract_frontmatter_slug(content: str) -> str | None:
    """Extract ``slug`` from YAML frontmatter, or ``None`` if absent.

    Only looks in the leading ``---`` fenced block.  The slug value is
    returned as-is (may be absolute ``/custom`` or relative ``custom``).

    Args:
        content: Raw Markdown/MDX source text.

    Returns:
        The slug string, or ``None`` when no frontmatter slug is declared.
    """
    fm = _FRONTMATTER_RE.match(content)
    if fm is None:
        return None
    slug_match = _SLUG_RE.search(fm.group(1))
    if slug_match is None:
        return None
    return slug_match.group(1).strip()


# ── Adapter ───────────────────────────────────────────────────────────────────


class DocusaurusAdapter:
    """Adapter for Docusaurus v3 documentation projects.

    Satisfies the :class:`~zenzic.core.adapters.BaseAdapter` protocol.

    Docusaurus geography:

    - Default locale docs: ``docs/`` (or custom ``docs_dir``).
    - Locale translations: ``i18n/{locale}/docusaurus-plugin-content-docs/current/``.
    - Both ``.md`` and ``.mdx`` extensions are valid source files.
    - Sidebar is typically auto-generated from the filesystem (all files
      ``REACHABLE``); explicit sidebar support is deferred to a future version.

    The adapter reads all structural metadata from ``BuildContext``
    (``zenzic.toml``).  ``baseUrl`` and ``routeBasePath`` are extracted from
    the Docusaurus config file via a multi-pattern static parser — no Node.js
    execution.

    Frontmatter ``slug:`` overrides the canonical URL in ``map_url()``.
    Callers must call ``set_slug_map()`` with pre-loaded file contents before
    building the VSM to enable slug support.

    Args:
        context: Build context from ``zenzic.toml``.
        docs_root: Resolved absolute path to the ``docs/`` directory.
        base_url: Docusaurus ``baseUrl`` (e.g. ``'/'``).
        route_base_path: Docusaurus ``routeBasePath`` (e.g. ``'docs'`` or ``''``).
    """

    def __init__(
        self,
        context: BuildContext,
        docs_root: Path,
        base_url: str = "/",
        route_base_path: str | None = None,
        versions: list[str] | None = None,
    ) -> None:
        self._docs_root = docs_root
        self._context = context
        self._base_url = base_url.rstrip("/") or ""
        # Docusaurus default routeBasePath is 'docs', but when docs are at
        # the site root it is ''.  None means "not set in config" → use
        # no prefix (docs are already relative to docs_root).
        self._route_base_path = route_base_path
        self._versions: tuple[str, ...] = tuple(versions or [])
        # The first entry in versions.json is the "latest" version; it serves
        # docs at the routeBasePath root (no version label in URL).
        self._latest_version: str | None = versions[0] if versions else None

        # Locale configuration from BuildContext (zenzic.toml).
        self._locale_dirs: frozenset[str] = frozenset(context.locales)
        self._fallback_to_default: bool = context.fallback_to_default

        # Docusaurus i18n geography: translations live under
        # i18n/{locale}/docusaurus-plugin-content-docs/current/
        # When scanning, these are mapped into the docs tree as locale prefixes.
        self._i18n_prefix = "i18n"
        self._plugin_docs_segment = "docusaurus-plugin-content-docs/current"

        # Slug map: rel_posix → slug.  Populated by set_slug_map().
        self._slug_map: dict[str, str] = {}

    def set_slug_map(self, md_contents: dict[Path, str]) -> None:
        """Pre-compute the slug map from frontmatter of all loaded files.

        Must be called before ``map_url()`` to enable frontmatter slug
        overrides.  Safe to call multiple times (last call wins).

        Args:
            md_contents: Pre-loaded mapping of absolute ``Path`` → raw content.
        """
        slugs: dict[str, str] = {}
        for abs_path, content in md_contents.items():
            try:
                rel = abs_path.relative_to(self._docs_root)
            except ValueError:
                continue
            slug = _extract_frontmatter_slug(content)
            if slug is not None:
                slugs[rel.as_posix()] = slug
        self._slug_map = slugs

    # ── BaseAdapter protocol ───────────────────────────────────────────────

    def is_locale_dir(self, part: str) -> bool:
        """Return ``True`` when *part* is a non-default locale directory name."""
        return part in self._locale_dirs

    def resolve_asset(self, missing_abs: Path, docs_root: Path) -> Path | None:
        """Return the default-locale fallback for a missing asset, or ``None``."""
        if not self._fallback_to_default:
            return None
        fallback = remap_to_default_locale(missing_abs, docs_root, self._locale_dirs)
        return fallback if fallback is not None and case_sensitive_exists(fallback) else None

    def resolve_anchor(
        self,
        resolved_file: Path,
        anchor: str,
        anchors_cache: dict[Path, set[str]],
        docs_root: Path,
    ) -> bool:
        """Return ``True`` if an anchor miss should be suppressed via i18n fallback.

        Docusaurus serves the default-locale page when a translation does not
        exist.  If the anchor exists in the default-locale equivalent, the
        miss is spurious.
        """
        if not self._fallback_to_default:
            return False
        default_file = remap_to_default_locale(resolved_file, docs_root, self._locale_dirs)
        if default_file is None:
            return False
        return anchor.lower() in anchors_cache.get(default_file, set())

    def is_shadow_of_nav_page(self, rel: Path, nav_paths: frozenset[str]) -> bool:
        """Return ``True`` when *rel* is a locale-mirror of a nav-listed page.

        In Docusaurus auto-generated sidebar mode, all files are nav-listed,
        so locale mirrors are always shadows of a nav page.
        """
        default_abs = remap_to_default_locale(
            self._docs_root / rel, self._docs_root, self._locale_dirs
        )
        if default_abs is None:
            return False
        return default_abs.relative_to(self._docs_root).as_posix() in nav_paths

    def get_ignored_patterns(self) -> set[str]:
        """Return filename patterns Docusaurus ignores.

        Docusaurus ignores files and directories starting with ``_``
        (e.g. ``_category_.json``, ``_private/``).
        """
        return {"_*"}

    def get_nav_paths(self) -> frozenset[str]:
        """Return nav-listed paths.

        With auto-generated sidebar (the Docusaurus default), all ``.md`` and
        ``.mdx`` files are navigable.  This method returns an empty frozenset
        to signal "no explicit nav" — ``classify_route()`` treats all files as
        ``REACHABLE`` in that case (same semantics as MkDocs without nav).
        """
        return frozenset()

    def has_engine_config(self) -> bool:
        """``True`` — DocusaurusAdapter is constructed only when a config exists."""
        return True

    def get_metadata_files(self) -> frozenset[str]:
        """Docusaurus configuration and sidebar files — shielded from Z903."""
        return frozenset(
            {
                "docusaurus.config.ts",
                "docusaurus.config.js",
                "docusaurus.config.mjs",
                "sidebars.ts",
                "sidebars.js",
                "versions.json",
                "_category_.json",
            }
        )

    # ── VSM integration ────────────────────────────────────────────────────

    def map_url(self, rel: Path) -> str:
        """Map a physical source path to its Docusaurus canonical URL.

        Resolution order:

        1. **Frontmatter slug** — if ``slug:`` is declared in frontmatter,
           it overrides the filesystem-derived URL.  An absolute slug
           (starts with ``/``) is used as-is; a relative slug replaces the
           last path segment.
        2. **Filesystem derivation** — strip extensions, collapse ``index``
           files to their parent directory.

        Docusaurus URL rules (filesystem):

        - Strip ``.md`` and ``.mdx`` extensions.
        - ``index.md(x)`` collapses to the parent directory URL.
        - Files prefixed with a numeric ordering (e.g. ``01-intro.mdx``) are
          served without the prefix **only** when ``_category_.json`` is
          present.  For safety, we preserve the full slug by default.

        Examples::

            guide/install.mdx   → /guide/install/
            guide/index.mdx     → /guide/
            index.mdx           → /
            checks.mdx          → /checks/

        With frontmatter ``slug: /custom-path``::

            guide/install.mdx   → /custom-path/

        Args:
            rel: Path of the source file relative to ``docs_root``.

        Returns:
            Canonical URL string with leading and trailing ``/``.
        """
        rel_posix = rel.as_posix()

        # ── Stage 1: frontmatter slug override ──
        slug = self._slug_map.get(rel_posix)
        if slug is not None:
            if slug.startswith("/"):
                # Absolute slug: always prefixed with routeBasePath.
                # Docusaurus: permalink = normalizeUrl([versionMetadata.path, docSlug])
                # where versionMetadata.path IS the routeBasePath.
                rbp = self._route_base_path if self._route_base_path is not None else "docs"
                url = slug.rstrip("/") or ""
                if rbp:
                    return "/" + rbp + url + "/"
                return url + "/" if url else "/"
            # Relative slug: replace the last path segment
            parent = rel.parent
            if parent == Path("."):
                return "/" + slug.strip("/") + "/"
            return "/" + parent.as_posix() + "/" + slug.strip("/") + "/"

        # ── Stage 2: filesystem-derived URL ──
        # Strip .md / .mdx extension
        stem = rel.with_suffix("")
        if stem.suffix == ".":
            # Handle edge case: file with no real stem after stripping
            stem = stem.with_suffix("")

        parts = list(stem.parts)

        locale = None
        if parts and parts[0] in self._locale_dirs:
            locale = parts.pop(0)

        version = None
        if parts and parts[0] == "_version_":
            parts.pop(0)
            if parts:
                version = parts.pop(0)

        # isCategoryIndex: collapse when name is 'index', 'readme', or matches
        # the immediate parent folder name (case-insensitive).
        # Mirrors Docusaurus isCategoryIndex() logic exactly.
        if parts:
            file_name_lower = parts[-1].lower()
            parent_name_lower = parts[-2].lower() if len(parts) >= 2 else None
            if (
                file_name_lower == "index"
                or file_name_lower == "readme"
                or (parent_name_lower is not None and file_name_lower == parent_name_lower)
            ):
                parts = parts[:-1]

        url_parts = []
        if locale:
            url_parts.append(locale)

        rbp = self._route_base_path if self._route_base_path is not None else "docs"
        if rbp:
            # Note: root routeBasePath is empty string
            url_parts.append(rbp)

        # The latest version (first entry in versions.json) is served at the
        # routeBasePath root — no version label in the URL.
        if version and version != self._latest_version:
            url_parts.append(version)

        url_parts.extend(parts)

        use_dir = True
        if getattr(self._context, "offline_mode", False):
            use_dir = False

        if not url_parts:
            return "/" if use_dir else "/index.html"

        if use_dir:
            return "/" + "/".join(url_parts) + "/"
        return "/" + "/".join(url_parts) + ".html"

    def classify_route(self, rel: Path, nav_paths: frozenset[str]) -> RouteStatus:
        """Classify a Docusaurus route.

        Classification rules (priority order):

        1. ``IGNORED`` — any path segment starts with ``_`` (Docusaurus
           convention for private/meta files like ``_category_.json``).
        2. ``REACHABLE`` — when no explicit nav is declared (auto-generated
           sidebar mode), all non-ignored files are reachable.
        3. ``REACHABLE`` — when the file is listed in ``nav_paths`` or is a
           locale shadow of a nav-listed page.
        4. ``ORPHAN_BUT_EXISTING`` — file exists but not in sidebar.

        Ghost Routes: locale index pages (e.g. ``it/index.mdx``) are
        auto-generated by Docusaurus i18n and marked ``REACHABLE`` even
        when they don't appear in any explicit sidebar.

        Args:
            rel:       Source path relative to ``docs_root``.
            nav_paths: Nav-listed paths from ``get_nav_paths()``.

        Returns:
            ``RouteStatus`` literal (never ``'CONFLICT'``).
        """
        # Rule 1: Private/meta files starting with _
        # Exemption: _version_ sentinel prefix is injected by ZenzicAdapter — not a real user dir.
        non_sentinel_parts = [p for p in rel.parts if p != "_version_"]
        if any(part.startswith("_") for part in non_sentinel_parts):
            return "IGNORED"

        # Draft files: check is deferred to frontmatter parsing (future).

        # Version Ghost Routes: all files under a known versioned_docs tree are REACHABLE.
        # The path sentinel prefix is _version_/<version_label>/...
        if len(rel.parts) >= 2 and rel.parts[0] == "_version_":
            return "REACHABLE"

        # Rule 2: No explicit nav → auto-generated sidebar → all REACHABLE
        if not nav_paths:
            return "REACHABLE"

        # Rule 3: Explicit nav match
        rel_posix = rel.as_posix()
        if rel_posix in nav_paths:
            return "REACHABLE"

        # Locale shadows inherit nav membership
        if self.is_shadow_of_nav_page(rel, nav_paths):
            return "REACHABLE"

        # Ghost Routes: locale entry points
        if rel.name in ("index.md", "index.mdx") and len(rel.parts) == 2:
            locale_dir = rel.parts[0]
            if locale_dir in self._locale_dirs:
                return "REACHABLE"

        # Rule 4: Not in nav
        return "ORPHAN_BUT_EXISTING"

    def get_route_info(self, rel: Path) -> RouteMetadata:
        """Return unified routing metadata for a Docusaurus source file.

        Resolution order:

        1. **Ignored** — files with path segments starting with ``_``.
        2. **Frontmatter slug** — if ``slug:`` is declared, it overrides the
           filesystem-derived URL.
        3. **Filesystem derivation** — standard Docusaurus clean-URL rules.

        Ghost Routes (locale entry points without physical files) are marked
        with ``is_proxy=True``.
        """
        from zenzic.core.adapters._base import RouteMetadata

        rel_posix = rel.as_posix()
        slug = self._slug_map.get(rel_posix)

        canonical_url = self.map_url(rel)
        nav_paths = self.get_nav_paths()
        status = self.classify_route(rel, nav_paths)

        # Detect proxy routes: locale entry points auto-generated by Docusaurus
        is_proxy = False
        if rel.name in ("index.md", "index.mdx") and len(rel.parts) == 2:
            locale_dir = rel.parts[0]
            if locale_dir in self._locale_dirs:
                is_proxy = True

        # Extract version from sentinel path prefix (_version_/<label>/...)
        version: str | None = None
        if len(rel.parts) >= 2 and rel.parts[0] == "_version_":
            version = rel.parts[1]

        return RouteMetadata(
            canonical_url=canonical_url,
            status=status,
            slug=slug,
            route_base_path=self._route_base_path if self._route_base_path is not None else "docs",
            is_proxy=is_proxy,
            version=version,
        )

    def provides_index(self, directory_path: Path) -> bool:
        """Return ``True`` when Docusaurus will generate a landing page for this directory.

        Docusaurus serves a directory landing page when any of the following
        conditions holds:

        * An ``index.md``, ``index.mdx``, ``README.md``, or ``README.mdx`` file
          exists directly inside *directory_path*.
        * A ``_category_.json`` exists with ``"link": {"type": "generated-index"}``,
          causing Docusaurus to auto-generate a category index page.

        I/O is permitted here — this method is called once per directory during
        the discovery phase, never inside per-link or per-file hot loops.

        Args:
            directory_path: Absolute path to the directory to inspect.

        Returns:
            ``True`` if the directory provides (or will generate) an index page.
        """
        index_files = ("index.md", "index.mdx", "README.md", "README.mdx")
        if any((directory_path / f).exists() for f in index_files):
            return True
        category_json = directory_path / "_category_.json"
        if category_json.exists():
            try:
                import json as _json

                data = _json.loads(category_json.read_text(encoding="utf-8"))
                link = data.get("link", {})
                return isinstance(link, dict) and link.get("type") == "generated-index"
            except Exception:  # noqa: BLE001
                return True  # conservative: assume it provides an index
        return False

    # ── Factory hook ───────────────────────────────────────────────────────

    @classmethod
    def from_repo(
        cls,
        context: BuildContext,
        docs_root: Path,
        repo_root: Path,
    ) -> DocusaurusAdapter:
        """Construct from a live repository root.

        Extracts ``baseUrl`` and ``routeBasePath`` from
        ``docusaurus.config.ts`` (or ``.js``) via static analysis.
        No Node.js execution — Pillar 2 compliance.

        Args:
            context: Build context from ``zenzic.toml``.
            docs_root: Resolved absolute ``docs/`` path.
            repo_root: Repository root (where ``docusaurus.config.*`` lives).

        Returns:
            Configured ``DocusaurusAdapter`` instance.
        """
        # Prefer the explicit base_url from zenzic.toml [build_context]
        # over static extraction from the JS/TS config file.
        config_path = find_docusaurus_config(repo_root)
        if context.base_url:
            base_url = context.base_url
        elif config_path:
            base_url = _extract_base_url(config_path)
        else:
            base_url = "/"

        import json

        versions: list[str] = []
        versions_json = repo_root / "versions.json"
        if versions_json.is_file():
            try:
                parsed = json.loads(versions_json.read_text(encoding="utf-8"))
                if isinstance(parsed, list):
                    versions = [str(v) for v in parsed]
            except Exception:
                pass

        route_base_path = _extract_route_base_path(config_path) if config_path else None
        return cls(context, docs_root, base_url, route_base_path, versions)

    def get_locale_source_roots(self, repo_root: Path) -> list[tuple[Path, str]]:
        """Return (locale_root, locale_name) pairs for all configured locales.

        Docusaurus i18n geography::

            i18n/{locale}/docusaurus-plugin-content-docs/current/

        Only returns entries where the directory exists on disk.

        Args:
            repo_root: Absolute repository root (parent of the ``i18n/``
                directory in a standard Docusaurus project).

        Returns:
            List of ``(absolute_locale_root, locale_name)`` tuples, one per
            locale declared in ``[build_context] locales`` that has a matching
            directory on disk.  Empty list when no locales are configured or
            none of their directories exist.
        """
        result: list[tuple[Path, str]] = []
        for locale in sorted(self._locale_dirs):
            root = (repo_root / self._i18n_prefix / locale / self._plugin_docs_segment).resolve()
            if root.is_dir():
                result.append((root, locale))

        for version in self._versions:
            # Default locale versioned docs
            v_root = (repo_root / f"versioned_docs/version-{version}").resolve()
            if v_root.is_dir():
                result.append((v_root, f"_version_/{version}"))

            # Translated versioned docs
            for locale in sorted(self._locale_dirs):
                vl_root = (
                    repo_root
                    / self._i18n_prefix
                    / locale
                    / "docusaurus-plugin-content-docs"
                    / f"version-{version}"
                ).resolve()
                if vl_root.is_dir():
                    result.append((vl_root, f"{locale}/_version_/{version}"))

        return result
