# SPDX-FileCopyrightText: 2026 PythonWoods <dev@pythonwoods.dev>
# SPDX-License-Identifier: Apache-2.0
"""DocusaurusAdapter — adapter for Docusaurus with native i18n support.

Docusaurus uses a fundamentally different geography from MkDocs:

- Source files live in ``docs/`` with ``.md`` or ``.mdx`` extensions.
- Translations live in ``i18n/{locale}/docusaurus-plugin-content-docs/current/``.
- The sidebar can be auto-generated from the filesystem or declared explicitly
  in ``sidebars.ts``.
- Frontmatter ``slug:`` overrides the canonical URL derived from the filepath.
- Clean URLs are the default: ``docs/guide/install.mdx`` → ``/docs/guide/install``.

Config parsing strategy (approved by Tech Lead):

- **Structural parameters** (locales, docs_dir, fallback) are read from
  ``.zenzic.toml`` via ``BuildContext`` — same as ``ZensicalAdapter``.
- **``baseUrl``** is extracted from ``docusaurus.config.ts`` or ``.js`` via a
  multi-pattern static parser (no Node.js subprocess — Pillar 2 compliance).
- **``routeBasePath``** is extracted from presets (e.g. ``@docusaurus/preset-classic``)
  when present.
- **``slug``** in frontmatter overrides the canonical URL in ``_map_url()``.
- **Sidebar** in ``autogenerated`` mode: all files are ``REACHABLE``.

When the config uses dynamic patterns that defeat static analysis (async
functions, dynamic imports, template literals), the parser falls back to
``'/'`` with a warning — never crashes, never guesses.

This module never imports or executes JavaScript.
"""

from __future__ import annotations

import logging
import unicodedata
from pathlib import Path
from typing import TYPE_CHECKING

from zenzic.core import regex as re
from zenzic.core.adapters._base import BaseAdapter
from zenzic.core.adapters._utils import (
    case_sensitive_exists,
    dedupe_roots,
    extract_frontmatter_tags,
    remap_to_default_locale,
)
from zenzic.models.config import BuildContext


if TYPE_CHECKING:
    from zenzic.core.adapters._base import RouteMetadata
    from zenzic.models.vsm import RouteStatus

_log = logging.getLogger(__name__)

# ── JS/TS comment stripping ──────────────────────────────────────────────────

# Matches single-line (//) and multi-line (/* */) comments, plus string
# literals (to avoid stripping comment-like text inside strings).
_COMMENT_RE = re.compile(
    r"//[^\n]*"  # single-line comment
    r"|/\*[\s\S]*?\*/"  # multi-line comment
    r'|"(?:[^"\\]|\\.)*"'  # double-quoted string (preserve)
    r"|'(?:[^'\\]|\\.)*'"  # single-quoted string (preserve)
    r"|`(?:[^`\\]|\\.)*`",  # template literal (preserve)
)


def _strip_js_comments(source: str) -> str:
    """Remove JS/TS comments while preserving string literals."""

    def _replacer(m: re.Match) -> str:
        text = m.group()
        if text.startswith("//"):
            return ""
        if text.startswith("/*"):
            return ""
        return text  # string literal — keep

    return _COMMENT_RE.sub(_replacer, source)


# ── Dynamic config detection ────────────────────────────────────────────────

# Patterns that indicate the config is dynamically generated and cannot be
# reliably parsed statically.
_DYNAMIC_PATTERNS = (
    re.compile(r"export\s+default\s+async\b"),
    re.compile(r"module\.exports\s*=\s*async\b"),
    re.compile(r"export\s+default\s+function\b"),
    re.compile(r"module\.exports\s*=\s*function\b"),
    re.compile(r"\bimport\s*\("),  # dynamic import()
    re.compile(r"\brequire\s*\("),  # CommonJS dynamic require
)


def _is_dynamic_config(content: str) -> bool:
    """Return ``True`` when the config uses patterns that defeat static analysis."""
    return any(pat.search(content) for pat in _DYNAMIC_PATTERNS)


# ── Config discovery ──────────────────────────────────────────────────────────


def find_docusaurus_config(repo_root: Path) -> Path | None:
    """Return the Docusaurus config file path, or ``None`` if absent.

    Checks for ``docusaurus.config.ts`` first,
    then falls back to ``docusaurus.config.js``.
    """
    for name in ("docusaurus.config.ts", "docusaurus.config.js"):
        candidate = repo_root / name
        if candidate.exists():
            return candidate
    return None


def find_docusaurus_site_root(docs_root: Path, repo_root: Path) -> Path:
    """Walk up the directory tree from docs_root to repo_root looking for docusaurus.config.ts or .js.

    If not found, falls back to repo_root.
    """
    curr = docs_root.resolve()
    target_repo = repo_root.resolve()
    while True:
        if (curr / "docusaurus.config.ts").is_file() or (curr / "docusaurus.config.js").is_file():
            return curr
        if curr == target_repo or curr == curr.parent:
            break
        curr = curr.parent
    return repo_root


# ── Static value extraction ──────────────────────────────────────────────────

# All patterns match the key in object-literal syntax:  key: 'value'
# or key: "value", with optional trailing comma and whitespace.

_BASE_URL_RE = re.compile(r"""baseUrl\s*:\s*['"]([^'"]+)['"]""")

_ROUTE_BASE_PATH_RE = re.compile(r"""routeBasePath\s*:\s*['"]([^'"]*?)['"]""")

# ── Blog plugin extraction (multi-root discovery) ───────────────────────────

# Detects ``blog: false`` (plugin disabled) anywhere in the preset body.
_BLOG_DISABLED_RE = re.compile(r"""blog\s*:\s*false\b""")

# Captures the body of a ``blog: { ... }`` block, single nesting level.
# Keeps the inner content so subsequent regexes can pull ``path`` and
# ``routeBasePath`` from it without false matches against unrelated keys
# (e.g. ``docs.routeBasePath``).
_BLOG_BLOCK_RE = re.compile(r"""blog\s*:\s*\{([^{}]*)\}""", re.DOTALL)

_BLOG_PATH_RE = re.compile(r"""\bpath\s*:\s*['"]([^'"]+)['"]""")
_BLOG_RBP_RE = re.compile(r"""\brouteBasePath\s*:\s*['"]([^'"]*?)['"]""")

# ── Infrastructure asset path extraction (Z404) ──────────────────────────────

# Matches: favicon: 'some/path' or favicon: "some/path"
_FAVICON_ASSET_RE = re.compile(r"""favicon\s*:\s*['"]([^'"]+)['"]""")

# Matches: image: 'path.png' — restricted to image extensions to avoid
# matching unrelated 'image:' keys (e.g. Docker image references).
_OG_IMAGE_ASSET_RE = re.compile(
    r"""(?:^|[^\w])image\s*:\s*['"]([^'"]+\.(?:png|jpg|jpeg|svg|gif|webp))['"]"""
)


def _extract_base_url(config_path: Path) -> str:
    """Extract ``baseUrl`` from a Docusaurus config file via static analysis.

    Multi-pattern parser that handles:
    - ``export default { baseUrl: '...' }``
    - ``module.exports = { baseUrl: '...' }``
    - ``const config = { baseUrl: '...' }; export default config;``

    Falls back to ``'/'`` when:
    - The file cannot be read.
    - The config uses async functions or dynamic imports (with warning).
    - The ``baseUrl`` key is not found in any recognised pattern.

    Args:
        config_path: Path to ``docusaurus.config.ts`` or ``.js``.

    Returns:
        The ``baseUrl`` string (e.g. ``'/'`` or ``'/docs/'``).
    """
    try:
        raw = config_path.read_text(encoding="utf-8")
    except OSError:
        return "/"

    content = _strip_js_comments(raw)

    if _is_dynamic_config(content):
        _log.warning(
            "Docusaurus config at %s uses dynamic patterns (async/import()/require()); "
            "falling back to baseUrl='/' — declare baseUrl in .zenzic.toml "
            "[build_context] to override.",
            config_path,
        )
        return "/"

    match = _BASE_URL_RE.search(content)
    return match.group(1) if match else "/"


def _extract_route_base_path(config_path: Path) -> str | None:
    """Extract ``routeBasePath`` from a Docusaurus config's preset/plugin block.

    Docusaurus presets (e.g. ``@docusaurus/preset-classic``) can override the
    docs URL prefix via ``docs.routeBasePath``.  When set to ``''``, docs are
    served at the site root instead of ``/docs/``.

    Returns ``None`` when ``routeBasePath`` is not found (caller should use
    the Docusaurus default ``'docs'``).

    Args:
        config_path: Path to ``docusaurus.config.ts`` or ``.js``.

    Returns:
        The ``routeBasePath`` string, or ``None`` when absent.
    """
    try:
        raw = config_path.read_text(encoding="utf-8")
    except OSError:
        return None

    content = _strip_js_comments(raw)

    if _is_dynamic_config(content):
        return None

    def find_braced_block(start_pos: int) -> str | None:
        brace_pos = content.find("{", start_pos)
        if brace_pos == -1:
            return None
        depth = 1
        i = brace_pos + 1
        while i < len(content) and depth > 0:
            char = content[i]
            if char == "{":
                depth += 1
            elif char == "}":
                depth -= 1
            i += 1
        if depth == 0:
            return content[brace_pos:i]
        return None

    # 1. Search for docs: { config block (typically inside preset options)
    for match in re.finditer(r"\bdocs\s*:\s*\{", content):
        block = find_braced_block(match.end() - 1)
        if block:
            rbp_match = _ROUTE_BASE_PATH_RE.search(block)
            if rbp_match:
                return rbp_match.group(1)

    # 2. Search for @docusaurus/plugin-content-docs config block
    for match in re.finditer(r"['\"]@docusaurus/plugin-content-docs['\"]", content):
        block = find_braced_block(match.end())
        if block:
            # Check if this instance is default (no id, or id: 'default')
            id_match = _PLUGIN_ID_RE.search(block)
            is_default = True
            if id_match:
                inst_id = id_match.group(1).strip()
                if inst_id != "default":
                    is_default = False
            if is_default:
                rbp_match = _ROUTE_BASE_PATH_RE.search(block)
                if rbp_match:
                    return rbp_match.group(1)

    # 3. Fallback to global routeBasePath match if nothing more specific was found
    fallback_match = _ROUTE_BASE_PATH_RE.search(content)
    if fallback_match:
        return fallback_match.group(1)

    return None


# ── Blog plugin discovery ───────────────────────────────────────────────────


def _extract_blog_config(config_path: Path) -> tuple[str, str] | None:
    """Extract ``(blog_path, blog_route_base_path)`` from a Docusaurus config.

    Discovers the ``blog`` plugin block inside the Docusaurus preset/plugin
    declaration via static analysis (no Node.js execution).  Honours the
    documented Docusaurus defaults: ``path = "blog"`` and
    ``routeBasePath = "blog"``.

    Returns ``None`` when:

    - The config file cannot be read.
    - The config uses dynamic patterns that defeat static analysis.
    - ``blog: false`` is declared (plugin explicitly disabled).
    - No ``blog: { ... }`` block is found AND no ``blog`` keyword appears
      (caller falls back to convention-over-config: scan ``<repo>/blog``).

    Args:
        config_path: Path to ``docusaurus.config.{ts,js,mjs}``.

    Returns:
        ``(blog_path, blog_route_base_path)`` or ``None``.
    """
    try:
        raw = config_path.read_text(encoding="utf-8")
    except OSError:
        return None

    content = _strip_js_comments(raw)

    if _is_dynamic_config(content):
        return None

    if _BLOG_DISABLED_RE.search(content):
        return None

    block = _BLOG_BLOCK_RE.search(content)
    if block is None:
        # No explicit blog block — caller decides whether to scan default location.
        return ("blog", "blog")

    body = block.group(1)
    path_match = _BLOG_PATH_RE.search(body)
    rbp_match = _BLOG_RBP_RE.search(body)

    blog_path = path_match.group(1) if path_match else "blog"
    blog_rbp = rbp_match.group(1) if rbp_match else "blog"
    return (blog_path, blog_rbp)


# ── Multi-instance content-docs plugin discovery ──────────────────────────────

# Captures every ``['@docusaurus/plugin-content-docs', { ... }]`` tuple in the
# Docusaurus config.  The brace body must be single-nesting (no inner objects)
# — adequate for the canonical multi-instance pattern documented at
# https://docusaurus.io/docs/docs-multi-instance.  Sibling instances that need
# nested objects (e.g. ``remarkPlugins: [require('foo', {opt: true})]``) fall
# through to the filesystem heuristic below, preserving Zero Subprocess.
_PLUGIN_CONTENT_DOCS_RE = re.compile(
    r"""['"]@docusaurus/plugin-content-docs['"]\s*,\s*\{([^{}]*)\}""",
    re.DOTALL,
)

_PLUGIN_ID_RE = re.compile(r"""\bid\s*:\s*['"]([^'"]+)['"]""")


def _extract_content_docs_instances(config_path: Path) -> list[tuple[str, str]]:
    """Extract sibling content-docs plugin instances from a Docusaurus config.

    Returns ``(instance_id, route_base_path)`` tuples for every
    ``['@docusaurus/plugin-content-docs', { id, path, routeBasePath, ... }]``
    entry found inside ``plugins: [ ... ]``.  The default docs instance
    (declared inside ``presets``) is **not** returned here — it is owned by
    :meth:`DocusaurusAdapter._route_base_path` and emitted separately.

    Falls back to ``[]`` when:

    - The config file cannot be read.
    - The config uses dynamic patterns (async / dynamic ``import()``).
    - No instance declares a static ``routeBasePath``.

    Args:
        config_path: Path to ``docusaurus.config.{ts,js,mjs,cjs}``.

    Returns:
        List of ``(id, route_base_path)`` tuples, in source order.
    """
    try:
        raw = config_path.read_text(encoding="utf-8")
    except OSError:
        return []

    content = _strip_js_comments(raw)
    if _is_dynamic_config(content):
        return []

    instances: list[tuple[str, str]] = []
    for match in _PLUGIN_CONTENT_DOCS_RE.finditer(content):
        body = match.group(1)
        rbp_match = _ROUTE_BASE_PATH_RE.search(body)
        if rbp_match is None:
            continue
        rbp = rbp_match.group(1)
        if not rbp:
            continue
        id_match = _PLUGIN_ID_RE.search(body)
        # Default instance has no ``id`` and lives in presets, never in plugins.
        instance_id = id_match.group(1) if id_match else rbp
        instances.append((instance_id, rbp))

    return instances


def check_config_assets(config_path: Path, repo_root: Path) -> list[tuple[str, str]]:
    """Check that infrastructure assets referenced in ``docusaurus.config.*`` exist.

    Extracts ``favicon`` and ``themeConfig.image`` (OG/social-card) values via
    static analysis and verifies the physical files exist inside the Docusaurus
    ``static/`` directory.

    No subprocess execution.  Only two existence checks (one per asset class)
    — safe to call during discovery phase outside hot-path loops.

    Args:
        config_path: Path to ``docusaurus.config.ts`` or ``.js``.
        repo_root:   Repository root (parent of ``static/``).

    Returns:
        List of ``(rel_path, message)`` tuples for each missing asset.
        ``rel_path`` is relative to ``repo_root`` (e.g.
        ``"static/assets/favicon/png/icon.png"``).  Empty list when all
        referenced assets exist or the config cannot be parsed.
    """
    try:
        raw = config_path.read_text(encoding="utf-8")
    except OSError:
        return []

    content = _strip_js_comments(raw)
    static_root = repo_root / "static"
    issues: list[tuple[str, str]] = []

    # -- favicon ------------------------------------------------------------
    favicon_match = _FAVICON_ASSET_RE.search(content)
    if favicon_match:
        asset_rel = favicon_match.group(1).lstrip("/")
        if not (static_root / asset_rel).exists():
            issues.append(
                (
                    f"static/{asset_rel}",
                    f"favicon asset not found on disk: "
                    f"'static/{asset_rel}' "
                    f"(declared as favicon: '{favicon_match.group(1)}' "
                    f"in {config_path.name}) [Z404]",
                )
            )

    # -- OG / social-card image -------------------------------------------
    # Take the first image-extension match; the themeConfig.image field is
    # always the first occurrence in a well-structured config.
    og_match = _OG_IMAGE_ASSET_RE.search(content)
    if og_match:
        asset_rel = og_match.group(1).lstrip("/")
        if not (static_root / asset_rel).exists():
            issues.append(
                (
                    f"static/{asset_rel}",
                    f"OG/social-card image not found on disk: "
                    f"'static/{asset_rel}' "
                    f"(declared as image: '{og_match.group(1)}' "
                    f"in {config_path.name}) [Z404]",
                )
            )

    return issues


# ── Frontmatter slug extraction ──────────────────────────────────────────────

_FRONTMATTER_RE = re.compile(r"\A\s*---\s*\n(.*?)\n---", re.DOTALL)
_SLUG_RE = re.compile(r"^slug\s*:\s*['\"]?([^'\"#\n]+?)['\"]?\s*$", re.MULTILINE)

# Docusaurus blog filename convention is ``YYYY-MM-DD-<slug>.mdx`` or ``YYYY/MM/DD-slug.mdx``.
_BLOG_DATE_FILENAME_RE = re.compile(
    r"^(?P<folder>.*?)(?P<date>\d{4}[-/]\d{1,2}[-/]\d{1,2})[-/]?(?P<text>.*?)(?:/index)?$"
)

# Slugification helpers (tag slugs — ASCII-only, mirrors MkDocs behaviour).
_SLUG_NONWORD_ASCII_RE = re.compile(r"[^\w\s-]", re.ASCII)
_SLUG_SPACES_RE = re.compile(r"\s+")

def _slugify_tag(tag: str) -> str:
    """Convert a raw frontmatter tag string to a Docusaurus-compatible URL slug.

    Mirrors Docusaurus's own tag slug algorithm:

    1. NFKD-normalise and strip combining characters (decomposes accented
       letters: ``à`` → ``a`` + combining grave, then drop the combining part).
    2. Lower-case.
    3. Strip characters that are neither word chars (``\\w``), spaces, nor
       hyphens.
    4. Collapse runs of whitespace to a single hyphen; strip leading/trailing
       hyphens.
    5. Return ``'untagged'`` as a safe fallback when the result is empty
       (e.g. a tag composed entirely of CJK characters).

    Args:
        tag: Raw tag string as found in frontmatter (e.g. ``'Python 3.10'``).

    Returns:
        URL-safe slug string (e.g. ``'python-310'``), or ``'untagged'``.
    """
    slug = unicodedata.normalize("NFKD", tag)
    slug = "".join(c for c in slug if not unicodedata.combining(c))
    slug = slug.lower()
    slug = _SLUG_NONWORD_ASCII_RE.sub("", slug)
    slug = _SLUG_SPACES_RE.sub("-", slug).strip("-")
    return slug or "untagged"


def _extract_frontmatter_slug(content: str) -> str | None:
    """Extract ``slug`` from YAML frontmatter, or ``None`` if absent.

    Only looks in the leading ``---`` fenced block.  The slug value is
    returned as-is (may be absolute ``/custom`` or relative ``custom``).

    Args:
        content: Raw Markdown/MDX source text.

    Returns:
        The slug string, or ``None`` when no frontmatter slug is declared.
    """
    fm = _FRONTMATTER_RE.match(content)
    if fm is None:
        return None
    slug_match = _SLUG_RE.search(fm.group(1))
    if slug_match is None:
        return None
    return slug_match.group(1).strip()


# ── Config navigation parser (navbar) ────────────────────────────────────────

# Matches: to: '/docs/intro' or to: "/docs/intro"
_NAVBAR_TO_RE = re.compile(r"""(?:^|[^\w])to\s*:\s*['"]([^'"]+)['"]""")

# Matches: docId: 'guide/install' or docId: "guide/install"
_NAVBAR_DOC_ID_RE = re.compile(
    r"""(?:^|[^\w])docId\s*:\s*['"]([a-zA-Z0-9][a-zA-Z0-9_/\-.]*?)['"]"""
)


def _parse_config_navigation(
    config_path: Path,
    docs_root: Path,
    base_url: str,
    route_base_path: str | None,
) -> frozenset[str]:
    """Extract doc paths from ``navbar`` declarations in ``docusaurus.config.*``.

    Docusaurus navbar items use two patterns to reference docs:

    * ``docId: 'guide/install'`` — a direct doc ID (same as sidebar IDs).
    * ``to: '/docs/guide/install'`` — a URL path that must be stripped of
      ``base_url`` and ``routeBasePath`` prefixes to recover the doc ID.

    Navbar and footer links do **not** create new routes in Docusaurus — routing
    is file-system driven by the docs plugin.  However, from a UX-discoverability
    standpoint, files linked from the navbar are reachable by users, so Zenzic
    must mark them ``REACHABLE`` even when they are absent from the sidebar.

    Extracted IDs are resolved to physical files by probing ``.md`` / ``.mdx``
    (and ``index.md`` / ``index.mdx`` for directory IDs), identical to the
    sidebar parser.  IDs with no matching file are silently dropped.

    Args:
        config_path:       Path to ``docusaurus.config.ts`` or ``.js``.
        docs_root:         Absolute path to the ``docs/`` directory.
        base_url:          Extracted ``baseUrl`` (e.g. ``'/'`` or ``'/project/'``).
        route_base_path:   Extracted ``routeBasePath`` (e.g. ``'docs'`` or ``''``).
                           ``None`` means not set → Docusaurus default ``'docs'``.

    Returns:
        Frozenset of posix paths with extension relative to ``docs_root``
        (e.g. ``frozenset({'changelog.md', 'guide/install.mdx'})``).
        Empty frozenset when nothing resolves.
    """
    try:
        raw = config_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return frozenset()

    content = _strip_js_comments(raw)

    # Normalise prefixes to strip from `to:` URL paths.
    rbp = (route_base_path if route_base_path is not None else "docs").strip("/")
    bu = base_url.strip("/")

    raw_ids: set[str] = set()

    # Pattern A: docId: 'some-id'  — direct doc ID, no prefix stripping needed.
    for m in _NAVBAR_DOC_ID_RE.finditer(content):
        raw_ids.add(m.group(1))

    # Pattern B: to: '/docs/guide/install'  — strip base_url + routeBasePath.
    for m in _NAVBAR_TO_RE.finditer(content):
        url_path = m.group(1).strip("/")
        # Strip baseUrl prefix first (e.g. 'my-project/docs/intro' → 'docs/intro')
        if bu and url_path.startswith(bu + "/"):
            url_path = url_path[len(bu) + 1 :]
        elif bu and url_path == bu:
            url_path = ""
        # Strip routeBasePath prefix (e.g. 'docs/intro' → 'intro')
        if rbp and url_path.startswith(rbp + "/"):
            url_path = url_path[len(rbp) + 1 :]
        elif rbp and url_path == rbp:
            url_path = ""
        if url_path:
            raw_ids.add(url_path)

    # Resolve IDs to physical files — same logic as _parse_sidebars.
    nav_paths: set[str] = set()
    for id_ in raw_ids:
        for ext in (".md", ".mdx"):
            candidate = docs_root / (id_ + ext)
            if candidate.exists():
                nav_paths.add(id_ + ext)
                break
        else:
            for ext in (".md", ".mdx"):
                candidate = docs_root / id_ / ("index" + ext)
                if candidate.exists():
                    nav_paths.add(f"{id_}/index{ext}")
                    break

    _log.debug(
        "config navigation parser: %d raw IDs → %d resolved paths from %s",
        len(raw_ids),
        len(nav_paths),
        config_path.name,
    )
    return frozenset(nav_paths)


# ── Sidebar parser ────────────────────────────────────────────────────────────

_SIDEBAR_AUTOGENERATED_RE = re.compile(r"""type\s*:\s*['"]autogenerated['"]""")
_SIDEBAR_DOC_ID_RE = re.compile(r"""(?:^|[^\w])id\s*:\s*['"]([a-zA-Z0-9][a-zA-Z0-9_/\-.]*?)['"]""")
_SIDEBAR_ARRAY_STRING_RE = re.compile(
    r"""(?:[\[,{]\s*|^\s*)['"]([a-zA-Z0-9][a-zA-Z0-9_/\-.]+)['"]""",
    re.MULTILINE,
)
_SIDEBAR_NON_ID_VALUES: frozenset[str] = frozenset(
    {
        "doc",
        "category",
        "link",
        "html",
        "autogenerated",
        "ref",
        "generated-index",
        "ts",
        "js",
        "mjs",
    }
)

_log_sidebar = logging.getLogger(__name__)


def _parse_sidebars(sidebar_path: Path, docs_root: Path) -> frozenset[str] | None:
    """Parse ``sidebars.ts`` or ``sidebars.js`` and return explicit nav paths.

    Resolution rules (Pillar 2 — no Node.js):

    1. If the file contains ``type: 'autogenerated'`` anywhere, return ``None``
       to signal "keep current all-REACHABLE behaviour".
    2. Otherwise extract doc IDs from two patterns:

       * ``{type: 'doc', id: 'foo/bar'}`` — explicit doc object.
       * Bare string literals in array/object contexts: ``['intro', 'guide/install']``.

    3. Resolve each raw ID to a physical file by probing ``.md`` then ``.mdx``
       (and ``index.md`` / ``index.mdx`` for directory IDs).  IDs with no
       matching file are silently dropped — false positives from label strings
       are naturally filtered by file-existence.

    Args:
        sidebar_path: Absolute path to ``sidebars.ts`` or ``sidebars.js``.
        docs_root:    Absolute path to the ``docs/`` directory.

    Returns:
        ``None`` — autogenerated mode detected; caller should use ``frozenset()``
                   so all files remain ``REACHABLE`` (current behaviour preserved).
        ``frozenset[str]`` — posix paths *with* extension relative to ``docs_root``
                             (e.g. ``'guide/install.md'``).  May be empty when no
                             IDs resolve to disk files.
    """
    try:
        content = sidebar_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        _log_sidebar.debug(
            "sidebar parser: cannot read %s — falling back to autogenerated mode",
            sidebar_path,
        )
        return None

    if _SIDEBAR_AUTOGENERATED_RE.search(content):
        _log_sidebar.debug(
            "sidebar parser: 'autogenerated' detected in %s — all files REACHABLE",
            sidebar_path.name,
        )
        return None

    raw_ids: set[str] = set()
    for m in _SIDEBAR_DOC_ID_RE.finditer(content):
        raw_ids.add(m.group(1))
    for m in _SIDEBAR_ARRAY_STRING_RE.finditer(content):
        val = m.group(1)
        if val not in _SIDEBAR_NON_ID_VALUES:
            raw_ids.add(val)

    nav_paths: set[str] = set()
    for id_ in raw_ids:
        for ext in (".md", ".mdx"):
            candidate = docs_root / (id_ + ext)
            if candidate.exists():
                nav_paths.add(id_ + ext)
                break
        else:
            for ext in (".md", ".mdx"):
                candidate = docs_root / id_ / ("index" + ext)
                if candidate.exists():
                    nav_paths.add(f"{id_}/index{ext}")
                    break

    _log_sidebar.debug(
        "sidebar parser: explicit nav — %d raw IDs → %d resolved paths",
        len(raw_ids),
        len(nav_paths),
    )
    return frozenset(nav_paths)


# ── Adapter ───────────────────────────────────────────────────────────────────


class DocusaurusAdapter(BaseAdapter):
    """Adapter for Docusaurus documentation projects.

    Satisfies the :class:`~zenzic.core.adapters.BaseAdapter` protocol.

    Docusaurus geography:

    - Default locale docs: ``docs/`` (or custom ``docs_dir``).
    - Locale translations: ``i18n/{locale}/docusaurus-plugin-content-docs/current/``.
    - Both ``.md`` and ``.mdx`` extensions are valid source files.
    - Sidebar is typically auto-generated from the filesystem (all files
      ``REACHABLE``); explicit sidebar support is deferred to a future version.

    The adapter reads all structural metadata from ``BuildContext``
    (``.zenzic.toml``).  ``baseUrl`` and ``routeBasePath`` are extracted from
    the Docusaurus config file via a multi-pattern static parser — no Node.js
    execution.

    Frontmatter ``slug:`` overrides the canonical URL in ``_map_url()``.
    Callers must call ``set_slug_map()`` with pre-loaded file contents before
    building the VSM to enable slug support.

    Args:
        context: Build context from ``.zenzic.toml``.
        docs_root: Resolved absolute path to the ``docs/`` directory.
        base_url: Docusaurus ``baseUrl`` (e.g. ``'/'``).
        route_base_path: Docusaurus ``routeBasePath`` (e.g. ``'docs'`` or ``''``).
    """

    def __init__(
        self,
        context: BuildContext,
        docs_root: Path,
        base_url: str = "/",
        route_base_path: str | None = None,
        versions: list[str] | None = None,
        site_root: Path | None = None,
    ) -> None:
        self._docs_root = docs_root
        self._context = context
        self._docusaurus_site_root = site_root if site_root is not None else docs_root.parent
        self._base_url = base_url.rstrip("/") or ""
        # Docusaurus default routeBasePath is 'docs', but when docs are at
        # the site root it is ''.
        if route_base_path is not None:
            self._route_base_path = route_base_path.strip("/")
        else:
            self._route_base_path = "docs"
        self._versions: tuple[str, ...] = tuple(versions or [])
        # The first entry in versions.json is the "latest" version; it serves
        # docs at the routeBasePath root (no version label in URL).
        self._latest_version: str | None = versions[0] if versions else None

        # Locale configuration from BuildContext (.zenzic.toml).
        self._locale_dirs: frozenset[str] = frozenset(context.locales)
        self._fallback_to_default: bool = context.fallback_to_default

        # Docusaurus i18n geography: translations live under
        # i18n/{locale}/docusaurus-plugin-content-docs/current/
        # When scanning, these are mapped into the docs tree as locale prefixes.
        self._i18n_prefix = "i18n"
        self._plugin_docs_segment = "docusaurus-plugin-content-docs/current"

        # Slug map: rel_posix → slug.  Populated by set_slug_map().
        self._slug_map: dict[str, str] = {}

        # Sidebar path — set by from_repo() when sidebars.ts or sidebars.js exists.
        # None means "no sidebar file found"; get_nav_paths() returns frozenset() (all REACHABLE).
        self._sidebar_path: Path | None = None

        # Config navigation paths — doc IDs extracted from navbar items in
        # docusaurus.config.*  Set eagerly by from_repo() so that get_nav_paths()
        # remains a pure aggregator with no I/O.
        self._navbar_paths: frozenset[str] = frozenset()

        # Multi-root discovery — blog plugin metadata.
        # Set eagerly by ``from_repo()`` when ``<repo>/blog`` exists or the
        # config declares the blog plugin.  ``_blog_root`` is the absolute
        # path to the blog content directory; ``_blog_route_base_path`` is the
        # URL prefix the engine will use (default ``'blog'``).
        self._blog_root: Path | None = None
        self._blog_route_base_path: str = "blog"

        # Sibling content-docs plugin instances (e.g. ``/developers/``).
        # Each tuple is ``(instance_id, route_base_path)``.  Populated by
        # ``from_repo()`` from the ``plugins: [ ... ]`` array OR from a
        # filesystem heuristic when static parsing fails.  Drives
        # :meth:`get_absolute_url_prefixes` so cross-plugin absolute links
        # bypass Z105 without any user-side config (Zero-Config invariant).
        self._content_docs_instances: tuple[tuple[str, str], ...] = ()

    def set_slug_map(self, md_contents: dict[Path, str]) -> None:
        """Pre-compute the slug map from frontmatter of all loaded files.

        Must be called before ``_map_url()`` to enable frontmatter slug
        overrides.  Safe to call multiple times (last call wins).

        Also handles blog files when ``_blog_root`` is set — the
        slug map key for those files is the blog-prefixed logical path
        (e.g. ``blog/2026-04-12-foo.mdx``) so ``_map_url()`` can resolve it
        without a second dispatch.

        Args:
            md_contents: Pre-loaded mapping of absolute ``Path`` → raw content.
        """
        slugs: dict[str, str] = {}
        for abs_path, content in md_contents.items():
            try:
                rel = abs_path.relative_to(self._docs_root)
                key = rel.as_posix()
            except ValueError:
                # Not under docs_root — try the blog root with prefix injection.
                if self._blog_root is not None and abs_path.is_relative_to(self._blog_root):
                    rel = abs_path.relative_to(self._blog_root)
                    key = (Path(self._blog_route_base_path) / rel).as_posix()
                else:
                    continue
            slug = _extract_frontmatter_slug(content)
            if slug is not None:
                slugs[key] = slug
        self._slug_map = slugs

    # ── BaseAdapter protocol ───────────────────────────────────────────────

    def is_locale_dir(self, part: str) -> bool:
        """Return ``True`` when *part* is a non-default locale directory name."""
        return part in self._locale_dirs

    def resolve_asset(self, missing_abs: Path, docs_root: Path) -> Path | None:
        """Return the default-locale fallback for a missing asset, or ``None``."""
        if not self._fallback_to_default:
            return None
        fallback = remap_to_default_locale(missing_abs, docs_root, self._locale_dirs)
        return fallback if fallback is not None and case_sensitive_exists(fallback) else None

    def resolve_anchor(
        self,
        resolved_file: Path,
        anchor: str,
        anchors_cache: dict[Path, set[str]],
        docs_root: Path,
    ) -> bool:
        """Return ``True`` if an anchor miss should be suppressed via i18n fallback.

        Docusaurus serves the default-locale page when a translation does not
        exist.  If the anchor exists in the default-locale equivalent, the
        miss is spurious.
        """
        if not self._fallback_to_default:
            return False
        default_file = remap_to_default_locale(resolved_file, docs_root, self._locale_dirs)
        if default_file is None:
            return False
        return anchor.lower() in anchors_cache.get(default_file, set())

    def is_shadow_of_nav_page(self, rel: Path, nav_paths: frozenset[str]) -> bool:
        """Return ``True`` when *rel* is a locale-mirror of a nav-listed page.

        In Docusaurus auto-generated sidebar mode, all files are nav-listed,
        so locale mirrors are always shadows of a nav page.
        """
        default_abs = remap_to_default_locale(
            self._docs_root / rel, self._docs_root, self._locale_dirs
        )
        if default_abs is None:
            return False
        return default_abs.relative_to(self._docs_root).as_posix() in nav_paths

    def get_ignored_patterns(self) -> set[str]:
        """Return filename patterns Docusaurus ignores.

        Docusaurus ignores files and directories starting with ``_``
        (e.g. ``_category_.json``, ``_private/``).
        """
        return {"_*"}

    def get_nav_paths(self) -> frozenset[str]:
        """Return all navigation-declared paths, or frozenset() when autogenerated.

        Aggregates two sources of UX-discoverable doc paths:

        1. **Sidebar** (``sidebars.ts`` / ``sidebars.js``) — explicit doc IDs
           listed in the sidebar tree.
        2. **Config navigation** (``docusaurus.config.*`` navbar items) — docs
           linked via ``to:`` URL paths or ``docId:`` attributes.

        A file absent from **both** sources is a true orphan (Z402): it exists
        on disk, has a Docusaurus-generated URL, but is not discoverable by
        users through any UI entry point.

        Returns ``frozenset()`` (no explicit nav → all files ``REACHABLE``) when:

        - No sidebar file is present (from_repo was not used, or the file does
          not exist) — backwards-compatible behaviour.
        - The sidebar uses ``type: 'autogenerated'`` — Docusaurus shows all
          docs in the sidebar, so all are discoverable.

        Returns:
            Frozenset of posix paths with extension relative to ``docs_root``
            (e.g. ``frozenset({'intro.mdx', 'guide/install.md'})``), or an
            empty frozenset signalling "no explicit nav".
        """
        if self._sidebar_path is not None:
            sidebar_paths = _parse_sidebars(self._sidebar_path, self._docs_root)
            if sidebar_paths is not None:
                # Explicit sidebar: merge with navbar paths.
                # A file is REACHABLE if it appears in the sidebar UI OR the navbar UI.
                return sidebar_paths | self._navbar_paths
        # Autogenerated or no sidebar: all files are already REACHABLE.
        return frozenset()

    def has_engine_config(self) -> bool:
        """``True`` — DocusaurusAdapter is constructed only when a config exists."""
        return True

    def get_metadata_files(self) -> frozenset[str]:
        """Docusaurus configuration and sidebar files — excluded from Z903."""
        return frozenset(
            {
                "docusaurus.config.ts",
                "docusaurus.config.js",
                "docusaurus.config.mjs",
                "sidebars.ts",
                "sidebars.js",
                "versions.json",
                "_category_.json",
            }
        )

    # ── VSM integration ────────────────────────────────────────────────────

    def _map_url(self, rel: Path) -> str:
        """Map a physical source path to its Docusaurus canonical URL.

        Resolution order and semantics:

        1. **Frontmatter slug** — if ``slug:`` is declared in frontmatter,
           it overrides the filesystem-derived URL.
           - For **Docs**: An absolute slug (starts with ``/``) is joined with
             the ``routeBasePath`` (``normalizeUrl([routeBasePath, slug])``).
             A relative slug replaces the last path segment (``resolvePathname(slug, dirSlug)``).
           - For **Blogs**: The ``routeBasePath`` is ALWAYS prepended, even for
             absolute slugs (e.g. ``slug: /custom`` -> ``/blog/custom/``).

        2. **Filesystem derivation** — strip extensions, collapse ``index``
           files to their parent directory.

        Docusaurus URL rules (filesystem):

        - Strip ``.md`` and ``.mdx`` extensions.
        - ``index.md(x)`` collapses to the parent directory URL.
        - **Blog dates**: If a blog file is prefixed with a date (e.g.
          ``2026-04-12-foo.mdx``), the date is extracted and transformed into
          path segments (``/2026/04/12/foo/``).
        - Files prefixed with a numeric ordering (e.g. ``01-intro.mdx``) are
          served without the prefix **only** when ``_category_.json`` is
          present.  For safety, we preserve the full slug by default.

        Examples::

            guide/install.mdx       → /guide/install/
            guide/index.mdx         → /guide/
            index.mdx               → /
            blog/2026-04-12-foo.mdx → /blog/2026/04/12/foo/

        With frontmatter ``slug: /custom-path``::

            guide/install.mdx   → /docs/custom-path/  (assuming docs routeBasePath is "docs")
            blog/my-post.mdx    → /blog/custom-path/  (assuming blog routeBasePath is "blog")

        Args:
            rel: Path of the source file relative to ``docs_root``.

        Returns:
            Canonical URL string with leading and trailing ``/``.
        """
        rel_posix = rel.as_posix()

        rel_posix = rel.as_posix()

        # ── Partial / private file guard ──
        # Docusaurus does not generate public routes for files or directories
        # that start with ``_`` (e.g. ``_category_.json``, ``_partials/``).  The
        # ``_version_`` prefix is an internal Zenzic marker — never a user dir.
        # Returning an empty string signals «no URL» to all callers.
        non_marker_parts = [p for p in rel.parts if p != "_version_"]
        if any(part.startswith("_") for part in non_marker_parts):
            return ""

        # Blog files arrive with the route_base_path prefix injected by the
        # caller (e.g. ``blog/2026-04-12-foo.mdx``).  Routing rules diverge
        # from docs:
        #   • Docusaurus blog plugin ALWAYS prepends routeBasePath, even for
        #     absolute frontmatter slugs (blogUtils.ts:303):
        #       normalizeUrl([baseUrl, routeBasePath, slug])
        #   • Date segment stripped from filename when no slug is present.
        #   • Frontmatter ``slug:`` always wins over the filename derivation.
        if self._blog_root is not None and rel.parts and rel.parts[0] == self._blog_route_base_path:
            slug_override = self._slug_map.get(rel_posix)
            if slug_override is not None:
                # normalizeUrl([baseUrl, "blog", slug]) — rbp unconditionally prepended.
                # Strip leading/trailing slashes from the slug value before joining.
                clean = slug_override.strip("/")
                rbp = self._blog_route_base_path
                if not clean:
                    # slug: "/" → normalizeUrl(["/", "blog", "/"]) = "/blog/"
                    return "/" + rbp + "/"
                return "/" + rbp + "/" + clean + "/"
            # Filename-derived slug: extract date segment from the path.
            # Docusaurus: parseBlogFileName.
            sub_path = Path(*rel.parts[1:]).with_suffix("").as_posix()

            match = _BLOG_DATE_FILENAME_RE.match(sub_path)
            if match:
                folder = match.group("folder") or ""
                date_str = match.group("date")
                text = match.group("text") or ""
                slug_date = date_str.replace("-", "/")
                parts = [slug_date]
                clean_folder = folder.strip("/")
                if clean_folder:
                    parts.append(clean_folder)
                if text:
                    parts.append(text)
                slug = "/" + "/".join(parts)
            else:
                if sub_path.lower() == "index":
                    slug = "/"
                elif sub_path.lower().endswith("/index"):
                    slug = "/" + sub_path[:-6]
                else:
                    slug = "/" + sub_path

            clean_slug = slug.strip("/")
            if not clean_slug:
                return "/" + self._blog_route_base_path + "/"
            return "/" + self._blog_route_base_path + "/" + clean_slug + "/"

        # Resolve the plugin instance and its routeBasePath.
        # Default to the main docs instance.
        rbp: str = self._route_base_path if self._route_base_path is not None else "docs"
        logical_rel = rel

        is_docs_subfolder = (
            rel.parts 
            and rel.parts[0] == "docs" 
            and (self._docs_root / "docs").is_dir()
        )

        if rel.parts:
            matched_instance = False
            # Check sibling instances first
            if self._content_docs_instances:
                for _inst_id, _inst_rbp in self._content_docs_instances:
                    if rel.parts[0] == _inst_id:
                        rbp = _inst_rbp
                        logical_rel = Path(*rel.parts[1:])
                        matched_instance = True
                        break
            
            # If not matched to sibling, check if it is default docs subfolder
            if not matched_instance and is_docs_subfolder:
                rbp = self._route_base_path if self._route_base_path is not None else "docs"
                logical_rel = Path(*rel.parts[1:])

        # ── Stage 1: frontmatter slug override (Docs plugin) ──
        # Pre-computed by set_slug_map() from already-in-memory content.
        # NEVER reads files here — all I/O happens in the VSM construction phase.
        mapped_slug = self._slug_map.get(rel_posix)

        rbp_norm = rbp.strip("/") if rbp else ""

        if mapped_slug is not None:
            if mapped_slug.startswith("/"):
                # ── Absolute slug ─────────────────────────────────────────────
                # Docusaurus docs.ts:185:
                #   permalink = normalizeUrl([versionMetadata.path, docSlug])
                #   normalizeUrl(["/docs/", "/absolute"]) → "/docs/absolute/"
                #
                # The absolute slug replaces the *directory component* but
                # routeBasePath (versionMetadata.path) is still prepended.
                # Only slug: "/" with no rbp yields the site root "/".
                clean = mapped_slug.strip("/")
                if rbp_norm:
                    if not clean:
                        # slug: "/" + rbp="docs" → "/docs/"
                        return "/" + rbp_norm + "/"
                    return "/" + rbp_norm + "/" + clean + "/"
                else:
                    # routeBasePath="" (docs-only mode): slug IS the full path
                    if not clean:
                        return "/"
                    return "/" + clean + "/"
            else:
                # ── Relative slug ─────────────────────────────────────────────
                # Docusaurus slug.ts: resolvePathname(slug, getDirNameSlug())
                # resolvePathname("rel-slug", "/guide/") → "/guide/rel-slug"
                # Then docs.ts: normalizeUrl(["/docs/", "/guide/rel-slug"]) →
                #   "/docs/guide/rel-slug/"
                #
                # getDirNameSlug(): sourceDirName="." → "/" else "/dir/"
                source_dir = logical_rel.parent
                if source_dir == Path("."):
                    dir_slug = "/"
                else:
                    dir_slug = "/" + source_dir.as_posix() + "/"

                # resolvePathname(slug, dir_slug): for non-traversal slugs,
                # this is simply dir_slug.rstrip("/") + "/" + clean.
                clean = mapped_slug.strip("/")
                resolved = dir_slug.rstrip("/") + "/" + clean if clean else dir_slug

                # Now prepend routeBasePath (normalizeUrl semantics).
                resolved_clean = resolved.strip("/")
                if rbp_norm:
                    if not resolved_clean:
                        return "/" + rbp_norm + "/"
                    return "/" + rbp_norm + "/" + resolved_clean + "/"
                else:
                    if not resolved_clean:
                        return "/"
                    return "/" + resolved_clean + "/"

        # ── Stage 2: filesystem-derived URL ──
        # Strip .md / .mdx extension
        stem_path = logical_rel.with_suffix("")
        if stem_path.suffix == ".":
            # Handle edge case: file with no real stem after stripping
            stem_path = stem_path.with_suffix("")

        parts = list(stem_path.parts)

        locale = None
        if parts and parts[0] in self._locale_dirs:
            locale = parts.pop(0)

        version = None
        if parts and parts[0] == "_version_":
            parts.pop(0)
            if parts:
                version = parts.pop(0)

        # isCategoryIndex: collapse when name is 'index', 'readme', or matches
        # the immediate parent folder name (case-insensitive).
        # Mirrors Docusaurus isCategoryIndex() logic exactly.
        if parts:
            file_name_lower = parts[-1].lower()
            parent_name_lower = parts[-2].lower() if len(parts) >= 2 else None
            if (
                file_name_lower == "index"
                or file_name_lower == "readme"
                or (parent_name_lower is not None and file_name_lower == parent_name_lower)
            ):
                parts = parts[:-1]

        url_parts = []
        if locale:
            url_parts.append(locale)

        if rbp_norm:
            url_parts.append(rbp_norm)

        # The latest version (first entry in versions.json) is served at the
        # routeBasePath root — no version label in the URL.
        if version and version != self._latest_version:
            url_parts.append(version)

        url_parts.extend(parts)

        use_dir = True
        if getattr(self._context, "offline_mode", False):
            use_dir = False

        if not url_parts:
            return "/" if use_dir else "/index.html"

        if use_dir:
            return "/" + "/".join(url_parts) + "/"
        return "/" + "/".join(url_parts) + ".html"

    def _classify_route(self, rel: Path, nav_paths: frozenset[str]) -> RouteStatus:
        """Classify a Docusaurus route.

        Classification rules (priority order):

        1. ``IGNORED`` — any path segment starts with ``_`` (Docusaurus
           convention for private/meta files like ``_category_.json``).
        2. ``REACHABLE`` — when no explicit nav is declared (auto-generated
           sidebar mode), all non-ignored files are reachable.
        3. ``REACHABLE`` — when the file is listed in ``nav_paths`` or is a
           locale shadow of a nav-listed page.
        4. ``ORPHAN_BUT_EXISTING`` — file exists but not in sidebar.

        Ghost Routes: locale index pages (e.g. ``it/index.mdx``) are
        auto-generated by Docusaurus i18n and marked ``REACHABLE`` even
        when they don't appear in any explicit sidebar.

        Args:
            rel:       Source path relative to ``docs_root``.
            nav_paths: Nav-listed paths from ``get_nav_paths()``.

        Returns:
            ``RouteStatus`` literal (never ``'CONFLICT'``).
        """
        # Rule 1: Private/meta files starting with _
        # Exemption: _version_ marker prefix is injected by ZenzicAdapter — not a real user dir.
        non_marker_parts = [p for p in rel.parts if p != "_version_"]
        if any(part.startswith("_") for part in non_marker_parts):
            return "IGNORED"

        # Blog posts are always reachable through the blog plugin
        # (paginated index, archive, tags).  No sidebar/nav membership needed.
        if self._blog_root is not None and rel.parts and rel.parts[0] == self._blog_route_base_path:
            return "REACHABLE"

        # Draft files: check is deferred to frontmatter parsing (future).

        # Version Ghost Routes: all files under a known versioned_docs tree are REACHABLE.
        # The path marker prefix is _version_/<version_label>/...
        if len(rel.parts) >= 2 and rel.parts[0] == "_version_":
            return "REACHABLE"

        # Rule 2: No explicit nav → auto-generated sidebar → all REACHABLE
        if not nav_paths:
            return "REACHABLE"

        # Rule 3: Explicit nav match
        rel_posix = rel.as_posix()
        if rel_posix in nav_paths:
            return "REACHABLE"

        # Locale shadows inherit nav membership
        if self.is_shadow_of_nav_page(rel, nav_paths):
            return "REACHABLE"

        # Ghost Routes: locale entry points
        if rel.name in ("index.md", "index.mdx") and len(rel.parts) == 2:
            locale_dir = rel.parts[0]
            if locale_dir in self._locale_dirs:
                return "REACHABLE"

        # Rule 4: Not in nav
        return "ORPHAN_BUT_EXISTING"

    def get_route_info(self, rel: Path) -> RouteMetadata:
        """Return unified routing metadata for a Docusaurus source file.

        Resolution order:

        1. **Ignored** — files with path segments starting with ``_``.
        2. **Frontmatter slug** — if ``slug:`` is declared, it overrides the
           filesystem-derived URL.
        3. **Filesystem derivation** — standard Docusaurus clean-URL rules.

        Ghost Routes (locale entry points without physical files) are marked
        with ``is_proxy=True``.
        """
        from zenzic.core.adapters._base import RouteMetadata

        rel_posix = rel.as_posix()

        # Blog files take a dedicated routing fast-path.  Their
        # canonical URL, status, and route_base_path are all derived from
        # the blog plugin metadata, never from the docs sidebar.
        if self._blog_root is not None and rel.parts and rel.parts[0] == self._blog_route_base_path:
            return RouteMetadata(
                canonical_url=self._map_url(rel),
                status="REACHABLE",
                slug=self._slug_map.get(rel_posix),
                route_base_path=self._blog_route_base_path,
                is_proxy=False,
                version=None,
            )

        slug = self._slug_map.get(rel_posix)

        # Resolve the plugin instance and its routeBasePath.
        rbp = self._route_base_path if self._route_base_path is not None else "docs"
        is_docs_subfolder = (
            rel.parts 
            and rel.parts[0] == "docs" 
            and (self._docs_root / "docs").is_dir()
        )
        if rel.parts:
            matched_instance = False
            if self._content_docs_instances:
                for _inst_id, _inst_rbp in self._content_docs_instances:
                    if rel.parts[0] == _inst_id:
                        rbp = _inst_rbp
                        matched_instance = True
                        break
            if not matched_instance and is_docs_subfolder:
                rbp = self._route_base_path if self._route_base_path is not None else "docs"

        # ── Early-return for partials / private Docusaurus files ──
        # Files or directories prefixed with ``_`` are not routed by Docusaurus
        # (e.g. ``_category_.json``, ``_partials/intro.mdx``).  Return an IGNORED
        # result with an empty URL *before* calling _map_url to avoid computing a
        # phantom URL that would trigger Z405 (UNDECLARED_SNIPPET) false-positives.
        # The ``_version_`` prefix is a Zenzic-internal marker and is excluded.
        non_marker_parts = [p for p in rel.parts if p != "_version_"]
        if any(part.startswith("_") for part in non_marker_parts):
            return RouteMetadata(
                canonical_url="",
                status="IGNORED",
                slug=None,
                route_base_path=rbp,
                is_proxy=False,
                version=None,
            )

        canonical_url = self._map_url(rel)
        nav_paths = self.get_nav_paths()
        status = self._classify_route(rel, nav_paths)

        # Detect proxy routes: locale entry points auto-generated by Docusaurus
        is_proxy = False
        if rel.name in ("index.md", "index.mdx") and len(rel.parts) == 2:
            locale_dir = rel.parts[0]
            if locale_dir in self._locale_dirs:
                is_proxy = True

        # Extract version from marker path prefix (_version_/<label>/...)
        version: str | None = None
        if len(rel.parts) >= 2 and rel.parts[0] == "_version_":
            version = rel.parts[1]

        return RouteMetadata(
            canonical_url=canonical_url,
            status=status,
            slug=slug,
            route_base_path=rbp,
            is_proxy=is_proxy,
            version=version,
        )

    def provides_index(self, directory_path: Path) -> bool:
        """Return ``True`` when Docusaurus will generate a landing page for this directory.

        Docusaurus serves a directory landing page when any of the following
        conditions holds:

        * An ``index.md``, ``index.mdx``, ``README.md``, or ``README.mdx`` file
          exists directly inside *directory_path*.
        * A ``_category_.json`` exists with ``"link": {"type": "generated-index"}``,
          causing Docusaurus to auto-generate a category index page.

        I/O is permitted here — this method is called once per directory during
        the discovery phase, never inside per-link or per-file hot loops.

        Args:
            directory_path: Absolute path to the directory to inspect.

        Returns:
            ``True`` if the directory provides (or will generate) an index page.
        """
        index_files = ("index.md", "index.mdx", "README.md", "README.mdx")
        if any((directory_path / f).exists() for f in index_files):
            return True
        category_json = directory_path / "_category_.json"
        if category_json.exists():
            try:
                import json as _json

                data = _json.loads(category_json.read_text(encoding="utf-8"))
                link = data.get("link", {})
                return isinstance(link, dict) and link.get("type") == "generated-index"
            except Exception:  # noqa: BLE001
                return True  # conservative: assume it provides an index
        return False

    def get_link_scheme_bypasses(self) -> frozenset[str]:
        """Return ``{"pathname"}`` — the Docusaurus static-asset routing escape hatch.

        Docusaurus uses ``pathname:///`` links to reference files under ``static/``
        that bypass the React router.  The leading ``/`` in the path component is a
        URI convention artifact, not a server-absolute path — suppressing Z105 for
        these links is correct and intentional (Rule R16, CEO-055).
        """
        return frozenset({"pathname"})

    # ── Factory hook ───────────────────────────────────────────────────────

    @classmethod
    def from_repo(
        cls,
        context: BuildContext,
        docs_root: Path,
        repo_root: Path,
    ) -> DocusaurusAdapter:
        """Construct from a live repository root.

        Extracts ``baseUrl`` and ``routeBasePath`` from
        ``docusaurus.config.ts`` (or ``.js``) via static analysis.
        No Node.js execution — Pillar 2 compliance.

        Args:
            context: Build context from ``.zenzic.toml``.
            docs_root: Resolved absolute ``docs/`` path.
            repo_root: Repository root (where ``docusaurus.config.*`` lives).

        Returns:
            Configured ``DocusaurusAdapter`` instance.
        """
        # Walk up from docs_root to find site_root containing Docusaurus config.
        site_root = find_docusaurus_site_root(docs_root, repo_root)

        # Prefer the explicit base_url from .zenzic.toml [build_context]
        # over static extraction from the JS/TS config file.
        config_path = find_docusaurus_config(site_root)
        if context.base_url:
            base_url = context.base_url
        elif config_path:
            base_url = _extract_base_url(config_path)
        else:
            base_url = "/"

        import json

        versions: list[str] = []
        versions_json = site_root / "versions.json"
        if versions_json.is_file():
            try:
                parsed = json.loads(versions_json.read_text(encoding="utf-8"))
                if isinstance(parsed, list):
                    versions = [str(v) for v in parsed]
            except Exception:
                pass

        route_base_path = _extract_route_base_path(config_path) if config_path else None

        sidebar_path: Path | None = None
        for _sidebar_name in ("sidebars.ts", "sidebars.js"):
            _candidate = site_root / _sidebar_name
            if _candidate.is_file():
                sidebar_path = _candidate
                break

        navbar_paths: frozenset[str] = frozenset()
        if config_path is not None:
            navbar_paths = _parse_config_navigation(
                config_path, docs_root, base_url, route_base_path
            )

        inst = cls(context, docs_root, base_url, route_base_path, versions, site_root=site_root)
        inst._sidebar_path = sidebar_path
        inst._navbar_paths = navbar_paths

        # ── Multi-root discovery: blog plugin auto-detection ──
        # Resolution order:
        #   1. Static parse of docusaurus.config.* for ``blog: { ... }``.
        #   2. Convention-over-config: if ``<repo>/blog`` exists, assume the
        #      default plugin layout (``path = 'blog'``, ``rbp = 'blog'``).
        #   3. Otherwise the blog plugin is absent — leave ``_blog_root`` None.
        blog_meta: tuple[str, str] | None = None
        if config_path is not None:
            blog_meta = _extract_blog_config(config_path)
        if blog_meta is None and (site_root / "blog").is_dir():
            blog_meta = ("blog", "blog")
        if blog_meta is not None:
            blog_path_str, blog_rbp = blog_meta
            blog_root = (site_root / blog_path_str).resolve()
            if blog_root.is_dir():
                inst._blog_root = blog_root
                inst._blog_route_base_path = blog_rbp

        # ── Multi-instance content-docs plugin auto-detection ──
        # Resolution order:
        #   1. Static parse of docusaurus.config.* for entries of the form
        #      ``['@docusaurus/plugin-content-docs', { id, routeBasePath }]``.
        #   2. Filesystem heuristic: pair every top-level repo directory with
        #      a sibling ``i18n/<locale>/docusaurus-plugin-content-docs-<id>/``
        #      folder.  When both exist, the directory name doubles as the
        #      route base path — covering projects whose config defeats static
        #      parsing while still preserving Zero Subprocess.
        instances: list[tuple[str, str]] = []
        if config_path is not None:
            instances.extend(_extract_content_docs_instances(config_path))

        if not instances:
            i18n_root = site_root / "i18n"
            if i18n_root.is_dir():
                seen: set[str] = set()
                for locale_dir in sorted(p for p in i18n_root.iterdir() if p.is_dir()):
                    for plugin_dir in locale_dir.iterdir():
                        name = plugin_dir.name
                        prefix = "docusaurus-plugin-content-docs-"
                        if not (plugin_dir.is_dir() and name.startswith(prefix)):
                            continue
                        instance_id = name[len(prefix) :]
                        if not instance_id or instance_id in seen:
                            continue
                        if (site_root / instance_id).is_dir():
                            seen.add(instance_id)
                            instances.append((instance_id, instance_id))

        inst._content_docs_instances = tuple(instances)

        return inst

    def get_locale_source_roots(self, repo_root: Path) -> list[tuple[Path, str]]:
        """Return (locale_root, locale_name) pairs for all configured locales.

        Docusaurus i18n geography::

            i18n/{locale}/docusaurus-plugin-content-docs/current/

        Only returns entries where the directory exists on disk.

        Args:
            repo_root: Absolute repository root (parent of the ``i18n/``
                directory in a standard Docusaurus project).

        Returns:
            List of ``(absolute_locale_root, locale_name)`` tuples, one per
            locale declared in ``[build_context] locales`` that has a matching
            directory on disk.  Empty list when no locales are configured or
            none of their directories exist.
        """
        result: list[tuple[Path, str]] = []
        site_root = self._docusaurus_site_root
        for locale in sorted(self._locale_dirs):
            root = (site_root / self._i18n_prefix / locale / self._plugin_docs_segment).resolve()
            if root.is_dir():
                result.append((root, locale))

        for version in self._versions:
            # Default locale versioned docs
            v_root = (site_root / f"versioned_docs/version-{version}").resolve()
            if v_root.is_dir():
                result.append((v_root, f"_version_/{version}"))

            # Translated versioned docs
            for locale in sorted(self._locale_dirs):
                vl_root = (
                    site_root
                    / self._i18n_prefix
                    / locale
                    / "docusaurus-plugin-content-docs"
                    / f"version-{version}"
                ).resolve()
                if vl_root.is_dir():
                    result.append((vl_root, f"{locale}/_version_/{version}"))

        return result

    def get_extra_content_roots(self, repo_root: Path) -> list[Path]:
        """Return all external content roots scanned outside docs_root."""
        roots: list[Path] = []
        if self._blog_root is not None and self._blog_root.is_dir():
            roots.append(self._blog_root.resolve())

        for instance_id, _route_base_path in self._content_docs_instances:
            candidate = (self._docusaurus_site_root / instance_id).resolve()
            if candidate.is_dir() and candidate != self._docs_root.resolve():
                roots.append(candidate)

        return dedupe_roots(roots)

    def get_absolute_url_prefixes(self, repo_root: Path | None = None) -> list[str]:  # noqa: ARG002
        """Return absolute URL prefixes owned by this Docusaurus project.

        Yields one prefix per active routing surface so cross-plugin links
        (the canonical multi-instance Docusaurus pattern) bypass Z105
        ABSOLUTE_PATH without any user-side configuration:

        - The default docs instance — ``/<route_base_path>/`` (commonly
          ``/docs/``; ``''`` means "served at the site root" which yields
          no prefix because every internal link would then start with
          ``/`` and the suppression would be vacuous).
                - The blog plugin — ``/<blog_route_base_path>/`` when the
          auto-detection located a blog content directory.
        - Every sibling ``@docusaurus/plugin-content-docs`` instance whose
          ``routeBasePath`` was discovered by ``from_repo`` (static parse
          of the JS/TS config or filesystem heuristic).

        Each prefix is normalised to ``/<segment>/`` so ``startswith``
        matches the route boundary (``/developers/intro`` matches but
        ``/developers-only/`` does not).

        Returns:
            List of absolute URL prefixes (each starting and ending with ``/``).
        """
        prefixes: set[str] = set()

        rbp = self._route_base_path if self._route_base_path is not None else "docs"
        if rbp:
            prefixes.add(f"/{rbp.strip('/')}/")

        if self._blog_root is not None and self._blog_route_base_path:
            prefixes.add(f"/{self._blog_route_base_path.strip('/')}/")

        for _instance_id, route_base_path in self._content_docs_instances:
            if route_base_path:
                prefixes.add(f"/{route_base_path.strip('/')}/")

        return sorted(prefixes)

    def get_virtual_routes(self, md_contents: dict[Path, str]) -> list[object]:
        """Return engine-generated virtual routes derived from blog frontmatter.

        Reads ``tags:`` and ``authors:`` from every blog post in
        ``md_contents``, slugifies each value, and emits the corresponding
        virtual routes (tags, authors, indices).
        """
        from zenzic.core.adapters._base import VirtualRoute

        if self._blog_root is None:  # CEO guard: blog plugin disabled
            return []

        tag_sources: dict[str, set[str]] = {}
        all_tagged_files: set[str] = set()
        all_blog_files: set[str] = set()
        
        # Track author keys/slugs to generate virtual routes
        author_keys: set[tuple[str, str | None]] = set()

        # Try to load global authors from authors.yml if it exists
        authors_yml = self._blog_root / "authors.yml"
        if authors_yml.is_file():
            try:
                import yaml
                with open(authors_yml, "r", encoding="utf-8") as f:
                    yml_data = yaml.safe_load(f)
                if isinstance(yml_data, dict):
                    for key, val in yml_data.items():
                        if isinstance(val, dict):
                            page_val = val.get("page")
                            if page_val is False:
                                continue
                            custom_permalink = None
                            if isinstance(page_val, dict):
                                custom_permalink = page_val.get("permalink")
                            author_slug = _slugify_author(key)
                            author_keys.add((author_slug, custom_permalink))
            except Exception:
                pass

        for abs_path, content in md_contents.items():
            if not abs_path.is_relative_to(self._blog_root):
                continue
            inner = abs_path.relative_to(self._blog_root)
            logical_rel = (Path(self._blog_route_base_path) / inner).as_posix()
            all_blog_files.add(logical_rel)

            # Extract tags
            tags = extract_frontmatter_tags(content)
            has_valid_tag = False
            for raw_tag in tags:
                slug = _slugify_tag(raw_tag)
                if slug and slug != "untagged":
                    tag_sources.setdefault(slug, set()).add(logical_rel)
                    has_valid_tag = True
            if has_valid_tag:
                all_tagged_files.add(logical_rel)

            # Extract authors from blog posts to cover inline authors and dynamically referenced keys
            post_authors = _extract_frontmatter_authors(content)
            for author_item in post_authors:
                author_slug = _slugify_author(author_item)
                # Check if this slug is already added (e.g. from authors.yml)
                if not any(ak[0] == author_slug for ak in author_keys):
                    author_keys.add((author_slug, None))

        routes: list[VirtualRoute] = []
        for slug, sources in tag_sources.items():
            routes.append(
                VirtualRoute(
                    url=f"/{self._blog_route_base_path}/tags/{slug}/",
                    label=f"tag:{slug}",
                    source_files=frozenset(sources),
                    kind="tag",
                )
            )

        if all_tagged_files:
            routes.append(
                VirtualRoute(
                    url=f"/{self._blog_route_base_path}/tags/",
                    label="tag_index",
                    source_files=frozenset(all_tagged_files),
                    kind="tag_index",
                )
            )

        # Generate author details virtual routes
        for author_slug, custom_permalink in author_keys:
            if custom_permalink:
                url = "/" + custom_permalink.strip("/") + "/"
            else:
                url = f"/{self._blog_route_base_path}/authors/{author_slug}/"
            routes.append(
                VirtualRoute(
                    url=url,
                    label=f"author:{author_slug}",
                    source_files=frozenset(all_blog_files),
                    kind="author",
                )
            )

        # Generate authors index virtual route
        if author_keys:
            routes.append(
                VirtualRoute(
                    url=f"/{self._blog_route_base_path}/authors/",
                    label="authors_index",
                    source_files=frozenset(all_blog_files),
                    kind="authors_index",
                )
            )

        return routes  # type: ignore[return-value]


def _slugify_author(name: str) -> str:
    """Convert an author name/key to a Docusaurus-compatible URL slug (lodash kebabCase)."""
    # Handle camelCase: insert hyphen before uppercase letter if preceded by lowercase letter
    s = re.sub(r'([a-z0-9])([A-Z])', r'\1-\2', name)
    slug = unicodedata.normalize("NFKD", s)
    slug = "".join(c for c in slug if not unicodedata.combining(c))
    slug = slug.lower()
    slug = _SLUG_NONWORD_ASCII_RE.sub("", slug)
    slug = _SLUG_SPACES_RE.sub("-", slug).strip("-")
    return slug or "unknown"


def _extract_frontmatter_authors(content: str) -> list[str]:
    """Extract author keys/slugs from YAML frontmatter."""
    fm = _FRONTMATTER_RE.match(content)
    if fm is None:
        return []
    try:
        import yaml
        data = yaml.safe_load(fm.group(1))
    except Exception:
        return []
    if not isinstance(data, dict):
        return []
    author_val = data.get("authors") or data.get("author")
    if not author_val:
        return []
    
    if isinstance(author_val, str):
        return [author_val.strip()]
    elif isinstance(author_val, list):
        slugs = []
        for item in author_val:
            if isinstance(item, str):
                slugs.append(item.strip())
            elif isinstance(item, dict):
                slug = item.get("slug")
                if slug:
                    slugs.append(str(slug).strip())
                elif item.get("key"):
                    slugs.append(str(item["key"]).strip())
        return slugs
    elif isinstance(author_val, dict):
        slug = author_val.get("slug")
        if slug:
            return [str(slug).strip()]
        elif author_val.get("key"):
            return [str(author_val["key"]).strip()]
    return []
