# SPDX-FileCopyrightText: 2026 PythonWoods <dev@pythonwoods.dev>
# SPDX-License-Identifier: Apache-2.0

name: Zenzic Actions Release

on:
  push:
    tags:
      - "actions-v*.*.*"

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: actions
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Setup uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2

      - name: Generate GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          generate_release_notes: true
